/* Inlines the stylesheet and every script into one self-contained HTML file
   that can be emailed, copied to a phone, or opened straight from disk.
   Usage: node build.mjs */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');

const ARTIFACT = process.argv.includes('--artifact');

let html = read('index.html');

// stylesheet
html = html.replace(
  /<link rel="stylesheet" href="css\/styles\.css">/,
  '<style>\n' + read('css/styles.css') + '\n</style>'
);

// the manifest and service worker have no meaning in a single local file
html = html.replace(/\s*<link rel="manifest"[^>]*>/, '');

// scripts, in document order
html = html.replace(/<script src="([^"]+)"><\/script>/g, (_, src) =>
  '<script>\n/* ===== ' + src + ' ===== */\n' + read(src) + '\n</script>');

let out, payload;

if (ARTIFACT) {
  // The artifact host supplies its own document skeleton, so ship the head
  // contents and the body markup only. There is no service worker there.
  const title = html.match(/<title>([\s\S]*?)<\/title>/)[1];
  const style = html.match(/<style>([\s\S]*?)<\/style>/)[0];
  const body = html.match(/<body>([\s\S]*)<\/body>/)[1];
  payload = '<title>' + title + '</title>\n' + style + '\n' +
            body.replace(/\n\s*navigator\.serviceWorker\.register\([^;]*;/,
                         '\n    return; // no service worker when hosted as an artifact')
                .replace('var CAN_SAVE_FILES = true; /* BUILD:CAN_SAVE_FILES */',
                         'var CAN_SAVE_FILES = false; // the artifact viewer blocks downloads')
                // strip the file-saving implementation itself, not just its call site
                .replace(/\/\* BUILD:SAVE_BODY_START \*\/[\s\S]*?\/\* BUILD:SAVE_BODY_END \*\//,
                         'return; // file saving is not available in the hosted build');
  out = 'artifact.html';
} else {
  payload = `<!--
  NCLEX-RN style adaptive practice exam - single file build
  Generated by build.mjs from the sources in this directory.
  Unofficial practice material. Not affiliated with NCSBN or Pearson VUE.
-->\n` + html;
  out = 'nclex-rn-practice-exam.html';
}

fs.writeFileSync(path.join(ROOT, out), payload);

const kb = (fs.statSync(path.join(ROOT, out)).size / 1024).toFixed(0);
const written = fs.readFileSync(path.join(ROOT, out), 'utf8');
if (/<script src=|<link rel="stylesheet"/.test(written)) {
  console.error('build failed: external references remain');
  process.exit(1);
}
if (ARTIFACT && /<!DOCTYPE|<html[\s>]|<head[\s>]|<\/body>|<\/html>/i.test(written)) {
  console.error('build failed: document skeleton must not be included in the artifact build');
  process.exit(1);
}
if (ARTIFACT && /serviceWorker\.register/.test(written)) {
  console.error('build failed: service worker registration left in the artifact build');
  process.exit(1);
}
if (ARTIFACT && !/var CAN_SAVE_FILES = false/.test(written)) {
  console.error('build failed: file-saving controls left enabled in the artifact build');
  process.exit(1);
}
if (ARTIFACT && /createObjectURL|download\s*=|BUILD:SAVE_BODY/.test(written)) {
  console.error('build failed: file-saving code remains in the artifact build');
  process.exit(1);
}
if (!ARTIFACT && !/var CAN_SAVE_FILES = true/.test(written)) {
  console.error('build failed: file-saving controls disabled in the downloadable build');
  process.exit(1);
}
console.log(`built ${out} (${kb} KB, no external references)`);
