/* Inlines the stylesheet and every script into one self-contained HTML file
   that can be emailed, copied to a phone, or opened straight from disk.
   Usage: node build.mjs */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const read = f => fs.readFileSync(path.join(ROOT, f), 'utf8');

let html = read('index.html');

// stylesheet
html = html.replace(
  /<link rel="stylesheet" href="css\/styles\.css">/,
  '<style>\n' + read('css/styles.css') + '\n</style>'
);

// the manifest and service worker have no meaning in a single local file
html = html.replace(/\s*<link rel="manifest"[^>]*>/, '');

// scripts, in document order
html = html.replace(/<script src="([^"]+)"><\/script>/g, (_, src) =>
  '<script>\n/* ===== ' + src + ' ===== */\n' + read(src) + '\n</script>');

const banner = `<!--
  NCLEX-RN style adaptive practice exam - single file build
  Generated by build.mjs from the sources in this directory.
  Unofficial practice material. Not affiliated with NCSBN or Pearson VUE.
-->\n`;

const out = 'nclex-rn-practice-exam.html';
fs.writeFileSync(path.join(ROOT, out), banner + html);

const kb = (fs.statSync(path.join(ROOT, out)).size / 1024).toFixed(0);
if (/<script src=|<link rel="stylesheet"/.test(fs.readFileSync(path.join(ROOT, out), 'utf8'))) {
  console.error('build failed: external references remain');
  process.exit(1);
}
console.log(`built ${out} (${kb} KB, no external references)`);
