/* Management of Care - NCLEX-RN Test Plan, Safe and Effective Care Environment */
(window.NCLEX_BANK = window.NCLEX_BANK || []).push(

{id:'MOC-001',cat:'MOC',b:-1.9,type:'mc',
 stem:'A charge nurse is assigning tasks on a medical unit. Which task is most appropriate to delegate to unlicensed assistive personnel (UAP)?',
 options:['Assisting a stable client with a bed bath','Teaching a newly diagnosed client to use an insulin pen','Assessing a client reporting new chest tightness','Adjusting the rate of a heparin infusion'],
 answer:0,
 rationale:'Delegation to UAP is limited to standardized, predictable tasks for stable clients. Bathing a stable client meets that description. Teaching, assessment, and titration of a high-alert infusion require the judgment of a registered nurse and cannot be delegated.'},

{id:'MOC-002',cat:'MOC',b:-1.5,type:'mc',
 stem:'Four clients are waiting to be seen. Which client should the nurse assess first?',
 options:['A client with a 2-day history of constipation','A client with an oxygen saturation of 86% on room air','A client requesting a refill of a stool softener','A client with a scheduled dressing change'],
 answer:1,
 rationale:'Airway, breathing, and circulation take priority. A saturation of 86% signals inadequate oxygenation and requires immediate assessment and intervention. The other three are routine or comfort needs that can safely wait.'},

{id:'MOC-003',cat:'MOC',b:-0.9,type:'mc',
 stem:'A client scheduled for surgery states, "I signed the consent, but I still do not understand what they are going to remove." What is the nurse\'s best action?',
 options:['Explain the surgical procedure in detail to the client','Notify the surgeon that the client has questions about the procedure','Reassure the client that the surgeon is highly experienced','Document that the client is anxious and proceed with preoperative care'],
 answer:1,
 rationale:'Informed consent is obtained by the practitioner performing the procedure. When a client expresses a lack of understanding, consent is not truly informed, and the nurse must notify the surgeon to return and clarify. The nurse witnesses the signature and advocates for the client but does not supply the procedural explanation.'},

{id:'MOC-004',cat:'MOC',b:-0.4,type:'mc',
 stem:'A nurse discovers that a colleague has documented a full assessment on a client who was off the unit for a procedure at that time. What is the nurse\'s priority action?',
 options:['Confront the colleague privately and ask them to correct the entry','Report the falsified documentation to the nurse manager','Write an incident report and place it in the client\'s chart','Ignore it, since no client harm occurred'],
 answer:1,
 rationale:'Falsified documentation is a serious legal and ethical breach that must be reported through the chain of command to the nurse manager. Incident reports are never filed in the client record, and the seriousness of falsification goes beyond a peer conversation.'},

{id:'MOC-005',cat:'MOC',b:0.2,type:'sata',
 stem:'A nurse is supervising a graduate nurse. Which actions by the graduate nurse require the supervising nurse to intervene? Select all that apply.',
 options:['Delegating vital sign measurement on a stable client to UAP','Asking a licensed practical nurse to develop the initial plan of care','Discussing a client\'s diagnosis with a family member in the hallway elevator','Verifying two client identifiers before administering a medication','Accepting a verbal order without reading it back to the prescriber','Wearing a gown and gloves to enter a contact-precautions room'],
 answer:[1,2,4],
 rationale:'Initial nursing assessment and creation of the plan of care cannot be delegated to an LPN. Discussing protected health information in a public area violates confidentiality. Verbal orders must be written down and read back to the prescriber. Delegating vital signs on a stable client, using two identifiers, and donning contact-precaution PPE are all correct.'},

{id:'MOC-006',cat:'MOC',b:0.7,type:'ordered',
 stem:'Place the steps the nurse should take when a client refuses a prescribed medication in the correct sequence.',
 options:['Ask the client about the reason for the refusal','Provide teaching about the purpose and expected effect of the medication','Honor the client\'s decision if the refusal continues','Notify the prescriber of the refusal','Document the refusal, the teaching given, and the notification'],
 rationale:'Begin by exploring the reason, because it may be based on a correctable misunderstanding or a side effect. Teaching follows. A competent adult retains the right to refuse, so that decision is honored. The prescriber must be notified so the plan can be revised, and the entire sequence is then documented.'},

{id:'MOC-007',cat:'MOC',b:-1.1,type:'mc',
 stem:'A client with a valid do-not-resuscitate (DNR) prescription becomes unresponsive and pulseless. What should the nurse do?',
 options:['Begin chest compressions and call a code','Provide comfort measures and notify the practitioner and family','Ask the family whether they want resuscitation started','Initiate rescue breathing but withhold compressions'],
 answer:1,
 rationale:'A valid DNR prescription directs the team to withhold cardiopulmonary resuscitation. The nurse provides comfort measures, other ordered care, and notifies the practitioner and family. Asking the family at the bedside to override a valid order is not appropriate.'},

{id:'MOC-008',cat:'MOC',b:1.1,type:'mc',
 stem:'A nurse on a busy unit receives four requests at the same time. Which requires the nurse\'s attention first?',
 options:['A postoperative client whose drainage device is full','A client with a heparin infusion whose aPTT result has just been reported as critical','A client asking for help to ambulate to the bathroom','A family member asking to speak with the practitioner'],
 answer:1,
 rationale:'A critical aPTT on a client receiving heparin signals a risk of serious bleeding and requires immediate evaluation and likely a change in the infusion. The other requests are important but do not carry an immediate threat of harm.'},

{id:'MOC-009',cat:'MOC',b:0.0,type:'mc',
 stem:'Which client is most appropriate to assign to a licensed practical nurse (LPN/LVN)?',
 options:['A client admitted 1 hour ago with new-onset atrial fibrillation','A client with stable chronic heart failure who needs daily weights and oral medications','A client receiving the first dose of intravenous vancomycin','A client requiring discharge teaching about a new colostomy'],
 answer:1,
 rationale:'LPN scope generally covers stable, predictable clients requiring reinforcement of teaching, oral medications, and routine monitoring. Newly admitted unstable clients, first doses of intravenous medications with reaction risk, and initial teaching are RN responsibilities.'},

{id:'MOC-010',cat:'MOC',b:-0.6,type:'mc',
 stem:'A client asks the nurse to be the witness for their advance directive. Which statement by the client indicates correct understanding of an advance directive?',
 options:['"It takes effect only after I am declared terminally ill."','"It states my wishes for care if I become unable to speak for myself."','"Once I sign it, I cannot change my mind."','"My insurance company decides whether it is followed."'],
 answer:1,
 rationale:'An advance directive documents a client\'s wishes for treatment should they lose decision-making capacity. It can be revised or revoked at any time by a competent client, does not require a terminal diagnosis, and is not controlled by an insurer.'},

{id:'MOC-011',cat:'MOC',b:1.4,type:'sata',
 stem:'A nurse is planning discharge for a client with new home oxygen therapy. Which referrals and actions are appropriate? Select all that apply.',
 options:['Arrange for a durable medical equipment supplier before discharge','Refer to home health nursing for safety assessment and teaching reinforcement','Confirm the client has working smoke detectors and no smoking in the home','Instruct the client to adjust the oxygen flow rate as needed for breathlessness','Verify transportation to the follow-up appointment','Discontinue the pulse oximeter teaching because it is not needed at home'],
 answer:[0,1,2,4],
 rationale:'Discharge planning includes equipment, home health follow-up, home safety around an oxidizer, and access to follow-up care. Clients must never self-titrate oxygen without a prescription, and home oximetry teaching supports safe self-monitoring rather than being unnecessary.'},

{id:'MOC-012',cat:'MOC',b:0.4,type:'mc',
 stem:'A nurse is caring for a client who does not speak English. What is the most appropriate way to obtain information about the client\'s pain?',
 options:['Ask the client\'s adult son to interpret','Use a qualified medical interpreter service','Use hand gestures and a picture of a face','Wait until the practitioner rounds with a bilingual colleague'],
 answer:1,
 rationale:'A qualified medical interpreter protects accuracy and confidentiality and is required for meaningful communication. Family members may filter or misinterpret information and may create a privacy concern. Gestures alone are inadequate for assessing pain, and delaying care is not acceptable.'},

{id:'MOC-013',cat:'MOC',b:-1.3,type:'mc',
 stem:'Which action by the nurse best demonstrates client advocacy?',
 options:['Completing the shift assignment quickly to avoid overtime','Requesting a palliative care consult after a client expresses a wish to stop aggressive treatment','Telling a client that the practitioner is always right','Deciding on the client\'s behalf which treatment they should accept'],
 answer:1,
 rationale:'Advocacy means supporting a client\'s expressed values and helping them access the services that match those values. Requesting palliative care after the client voices their wishes does this. Deciding for the client or discouraging questions undermines autonomy.'},

{id:'MOC-014',cat:'MOC',b:1.8,type:'mc',
 stem:'During a mass casualty event using standard triage, which client should be tagged as the highest priority for immediate treatment?',
 options:['A client with an open femur fracture, alert, radial pulse present','A client with a tension pneumothorax and severe respiratory distress','A client with full-thickness burns to 90% of the body surface, unresponsive, agonal breathing','A client with a laceration to the forearm that is controlled with a dressing'],
 answer:1,
 rationale:'Immediate (red) triage is reserved for life-threatening injuries that are survivable with rapid intervention. A tension pneumothorax is rapidly reversible with decompression. Injuries incompatible with survival given available resources are tagged expectant, a stable fracture is delayed, and a minor laceration is minimal.'},

{id:'MOC-015',cat:'MOC',b:0.9,type:'mc',
 stem:'A nurse identifies that a client received a duplicate dose of a scheduled medication. After assessing the client, which action should the nurse take next?',
 options:['Document the extra dose only in the incident report','Notify the prescriber and complete an occurrence report','Ask the previous nurse to correct the medication record','Observe the client for 24 hours before reporting'],
 answer:1,
 rationale:'After ensuring client safety, the nurse notifies the prescriber so that monitoring or treatment can be ordered, and completes an occurrence report for quality review. The dose given must also be documented in the medical record; the occurrence report is a separate risk-management document.'},

{id:'MOC-016',cat:'MOC',b:-0.2,type:'mc',
 stem:'Which situation requires the nurse to obtain a new informed consent before proceeding?',
 options:['A client scheduled for a right knee arthroscopy states the left knee is the painful one','A client asks how long the procedure will take','A client requests a family member be present in the preoperative area','A client asks whether they may have water before surgery'],
 answer:0,
 rationale:'A discrepancy between the consented site and the client\'s report is a wrong-site surgery risk. The procedure must stop, the surgeon must be notified, and consent must be corrected and re-obtained before proceeding.'},

{id:'MOC-017',cat:'MOC',b:0.5,type:'sata',
 stem:'Which entries are appropriate for the nurse to include in the client\'s medical record? Select all that apply.',
 options:['"Client ambulated 20 feet in the hallway with a standby assist."','"Client appears to be drug-seeking."','"Client rates incisional pain 7 of 10 before medication and 3 of 10 at 45 minutes."','"Notified Dr. Lee at 1420 of temperature 38.9 C; no new prescriptions received."','"Family is difficult and demanding."','"Dressing dry and intact; no drainage noted."'],
 answer:[0,2,3,5],
 rationale:'Documentation must be objective, factual, and measurable. Labels such as "drug-seeking" or "difficult" are subjective judgments that can harm the client and expose the nurse legally. Observable behavior, quantified data, and communication with the practitioner are appropriate.'},

{id:'MOC-018',cat:'MOC',b:1.6,type:'mc',
 stem:'A nurse manager reviews unit data showing a rise in catheter-associated urinary tract infections. Which action best reflects the quality improvement process?',
 options:['Post the infection rate in the break room and ask staff to be more careful','Convene a team to review insertion and maintenance practices, then test a change','Assign the nurse with the most infections to remedial education','Order a different brand of catheter immediately'],
 answer:1,
 rationale:'Quality improvement analyzes the process rather than blaming individuals, then tests a targeted change and remeasures. Posting data without a plan, singling out a nurse, or changing supplies without analysis do not address root causes.'},

{id:'MOC-019',cat:'MOC',b:-0.7,type:'mc',
 stem:'A client\'s neighbor calls the unit and asks how the client is doing. What is the nurse\'s best response?',
 options:['"The client is stable and should go home tomorrow."','"I am not able to share any information about who is here."','"Let me connect you to the client\'s room."','"Only immediate family can receive information."'],
 answer:1,
 rationale:'Confirming that a person is a client is itself protected information unless the client has agreed to be listed in the facility directory. The safest response neither confirms nor denies the admission. Transferring the call would also confirm the admission.'},

{id:'MOC-020',cat:'MOC',b:0.3,type:'mc',
 stem:'The nurse is preparing a hand-off report using SBAR. Which piece of information belongs in the "recommendation" section?',
 options:['"The client had a total hip replacement yesterday."','"The client\'s blood pressure is 86/50 and heart rate is 118."','"I think the client needs a fluid bolus and re-evaluation now."','"The client has a history of hypertension and diabetes."'],
 answer:2,
 rationale:'In SBAR, Situation states the problem, Background gives context, Assessment gives the current findings and interpretation, and Recommendation states what the nurse is asking for. A request for a bolus and re-evaluation is the recommendation.'},

{id:'MOC-021',cat:'MOC',b:1.2,type:'mc',
 stem:'A nurse is floated from a medical unit to a pediatric unit and is assigned four children. What is the most appropriate action?',
 options:['Refuse the assignment and leave the unit','Accept the assignment and provide care within their competence, notifying the charge nurse of any tasks outside it','Accept the full assignment and look up unfamiliar skills as needed','Ask a parent to perform tasks the nurse is unfamiliar with'],
 answer:1,
 rationale:'Abandoning an accepted assignment is unsafe and can be grounds for discipline, but so is performing skills outside one\'s competence. The correct approach is to accept care within competence and negotiate a modified assignment with the charge nurse for the rest.'},

{id:'MOC-022',cat:'MOC',b:-1.0,type:'mc',
 stem:'Which client should the nurse assess first at the beginning of the shift?',
 options:['A client with a temperature of 38.1 C who received an antipyretic 30 minutes ago','A client 1 day postoperative who is reporting incisional pain of 6 of 10','A client with new confusion and a pulse oximetry reading of 88%','A client waiting for a ride home after discharge'],
 answer:2,
 rationale:'New confusion combined with hypoxemia suggests an acute change in oxygenation or perfusion and takes priority. A treated fever, expected postoperative pain, and a discharge wait are all lower priority.'},

{id:'MOC-023',cat:'MOC',b:0.8,type:'sata',
 stem:'Which actions are within the registered nurse\'s scope when a client requires restraints for violent behavior? Select all that apply.',
 options:['Initiate restraints in an emergency before the prescription is obtained','Obtain a practitioner prescription as soon as possible after initiation','Apply restraints as a convenience when the unit is short-staffed','Assess circulation, skin, and toileting needs at required intervals','Use the least restrictive device that ensures safety','Leave the restraint prescription as a standing order for the admission'],
 answer:[0,1,3,4],
 rationale:'Restraints may be initiated in an emergency with a prescription obtained promptly afterward, must be the least restrictive effective option, and require frequent monitoring. Restraints may never be used for staff convenience, and standing or as-needed restraint orders are prohibited.'},

{id:'MOC-024',cat:'MOC',b:2.0,type:'mc',
 stem:'A nurse receives a telephone prescription during an emergency. Which action best meets the standard for safe verbal order management?',
 options:['Enter the order and administer, then verify with the prescriber the next day','Write the order down, read it back to the prescriber, and receive confirmation','Ask a second nurse to listen while the prescriber speaks, then administer','Record the order in the nurse\'s personal notes until the prescriber signs'],
 answer:1,
 rationale:'The accepted standard is write down, read back, and receive verbal confirmation from the prescriber. Having a witness listen does not replace read-back, delayed verification does not prevent error, and orders belong in the medical record rather than personal notes.'},

{id:'MOC-025',cat:'MOC',b:-1.6,type:'mc',
 stem:'Which task may the nurse delegate to unlicensed assistive personnel?',
 options:['Measuring and recording intake and output','Evaluating whether a client tolerated ambulation','Changing a sterile central line dressing','Administering an as-needed antiemetic'],
 answer:0,
 rationale:'Measuring and recording intake and output is a routine data-collection task with a predictable outcome. Evaluation, sterile central line care, and medication administration require licensed judgment and skill.'},

{id:'MOC-026',cat:'MOC',b:0.1,type:'mc',
 stem:'A client with decision-making capacity refuses a blood transfusion on religious grounds despite a hemoglobin of 6.2 g/dL. What is the nurse\'s best action?',
 options:['Administer the transfusion because the client\'s life is at risk','Support the client\'s decision and notify the practitioner and the ethics resource','Ask the family to sign the consent instead','Tell the client they will die without the transfusion so they change their mind'],
 answer:1,
 rationale:'A competent adult has the right to refuse treatment, even life-sustaining treatment. The nurse supports the decision, notifies the team so alternatives can be explored, and can involve ethics resources. Coercion and substituted family consent for a capable client are not acceptable.'},

{id:'MOC-027',cat:'MOC',b:1.0,type:'mc',
 stem:'The charge nurse must assign a client with active pulmonary tuberculosis to a room. Which room assignment is correct?',
 options:['A private room with negative pressure and an anteroom','A private room with positive pressure airflow','A semiprivate room with a client who has had tuberculosis previously','Any private room with the door kept open for observation'],
 answer:0,
 rationale:'Pulmonary tuberculosis requires airborne precautions, meaning an airborne infection isolation room with negative pressure, at least 6 to 12 air changes per hour, and the door kept closed. Positive pressure rooms are for protective isolation of immunocompromised clients.'},

{id:'MOC-028',cat:'MOC',b:-0.3,type:'mc',
 stem:'A nurse is reviewing prescriptions written for four clients. Which prescription should the nurse question?',
 options:['Furosemide 40 mg IV push over 2 minutes','Potassium chloride 20 mEq IV push','Regular insulin 6 units subcutaneously before meals','Acetaminophen 650 mg orally every 6 hours as needed'],
 answer:1,
 rationale:'Potassium chloride is never administered by intravenous push; doing so can cause fatal cardiac arrest. It must be diluted and infused at a controlled rate. The other prescriptions are within normal ranges and routes.'},

{id:'MOC-029',cat:'MOC',b:1.5,type:'ordered',
 stem:'A nurse finds a client on the floor beside the bed. Place the nurse\'s actions in the correct order.',
 options:['Assess the client\'s level of consciousness, airway, breathing, and circulation','Perform a focused assessment for injury and take vital signs','Call for assistance and return the client to bed using safe technique','Notify the practitioner and the client\'s family','Document the event objectively and complete an occurrence report'],
 rationale:'Client assessment comes before movement, because moving a client with a possible spinal or extremity injury can cause harm. A focused injury assessment follows, then safe repositioning with help, then notification, and finally documentation and the occurrence report.'},

{id:'MOC-030',cat:'MOC',b:0.6,type:'mc',
 stem:'A nurse suspects that a coworker is impaired at work. What is the nurse\'s priority action?',
 options:['Confront the coworker at the nurses\' station','Report the observations to the nursing supervisor immediately','Wait to see whether the behavior recurs on the next shift','Offer to take over the coworker\'s assignment quietly'],
 answer:1,
 rationale:'Client safety requires that a possibly impaired practitioner be removed from client care immediately. The nurse reports specific, objective observations to the supervisor. Delaying or covering the assignment leaves clients at risk and may violate the nurse practice act.'},

{id:'MOC-031',cat:'MOC',b:-0.5,type:'mc',
 stem:'Which of these is the best example of the nurse using the nursing process to evaluate care?',
 options:['Reviewing whether the client\'s pain score decreased after the intervention','Listing the client\'s home medications on admission','Setting a goal that the client will ambulate 50 feet by day 2','Documenting that a dressing change was completed'],
 answer:0,
 rationale:'Evaluation compares the client\'s actual response with the expected outcome. Collecting a medication list is assessment, writing a measurable goal is planning, and charting a completed task is implementation.'},

{id:'MOC-032',cat:'MOC',b:1.3,type:'sata',
 stem:'A nurse is coordinating care for a client being discharged to a skilled nursing facility. Which information must be included in the transfer report? Select all that apply.',
 options:['Code status and advance directive documentation','Current medications with the time of the last dose','Isolation precautions and pending culture results','The client\'s religious affiliation for staff assignment purposes','Wound status, drains, and the last dressing change','Baseline functional and cognitive status'],
 answer:[0,1,2,4,5],
 rationale:'Safe transitions require code status, an accurate medication reconciliation, infection precautions, wound and device status, and baseline function. Religious affiliation may be shared to support care preferences, but it is not used to determine staff assignment and is not required transfer content.'},

{id:'MOC-033',cat:'MOC',b:2.2,type:'mc',
 stem:'A nurse working in a state with mandatory reporting suspects elder abuse after seeing patterned bruising and a caregiver who answers all questions for the client. The client denies abuse. What should the nurse do?',
 options:['Take no action because the client denies abuse','Report the suspicion to adult protective services as required by law','Wait until the injuries are confirmed by radiography','Ask the caregiver to leave and then discharge the client home'],
 answer:1,
 rationale:'Mandatory reporting requires a report based on reasonable suspicion, not proof, and a client\'s denial does not remove the duty. The nurse reports, documents objective findings, and interviews the client separately from the caregiver.'},

{id:'MOC-034',cat:'MOC',b:-0.8,type:'mc',
 stem:'A client\'s family member asks to read the medical record. What is the nurse\'s best response?',
 options:['"Records are confidential and no one may read them."','"I will ask the client whether they authorize you to review the record."','"You may read it once the client is discharged."','"Only the practitioner can share the record with you."'],
 answer:1,
 rationale:'Access is controlled by the client. The nurse checks whether the client authorizes disclosure and then follows the facility process for record access. A blanket refusal or deferral misstates the client\'s right to authorize.'},

{id:'MOC-035',cat:'MOC',b:0.45,type:'matrix',
 stem:'The charge nurse is making assignments for the shift. Indicate whether each assignment is appropriate or requires reassignment.',
 rowHeader:'Assignment',
 rows:['Assign a 2-hour-postoperative client with an epidural infusion to a registered nurse',
       'Assign an unlicensed assistive person to obtain a clean-catch urine specimen from a stable client',
       'Assign a licensed practical nurse to reinforce previously taught crutch walking',
       'Assign an unlicensed assistive person to assess a new pressure injury',
       'Assign a licensed practical nurse to administer the first dose of intravenous ceftriaxone'],
 cols:['Appropriate','Requires reassignment'],
 answer:[0,0,0,1,1],
 rationale:'Unstable and high-acuity clients and first doses of intravenous antibiotics require registered nurse judgment. Specimen collection and reinforcing prior teaching are within the scope of assistive and practical nursing personnel. Assessment of a new wound is a registered nurse responsibility.'},

{id:'MOC-036',cat:'MOC',b:1.7,type:'mc',
 stem:'A client tells the nurse, "I am leaving now. I do not care what the doctor says." Which action should the nurse take first?',
 options:['Physically block the door until security arrives','Explain the risks of leaving and ask the client to sign the against-medical-advice form','Assess the client\'s reason for wanting to leave and their decision-making capacity','Call the family to persuade the client to stay'],
 answer:2,
 rationale:'Before any paperwork, the nurse determines why the client wants to leave and whether the client has capacity, because a correctable problem such as uncontrolled pain or a misunderstanding may resolve the situation. Physically preventing a capable client from leaving constitutes false imprisonment.'},

{id:'MOC-037',cat:'MOC',b:-1.4,type:'mc',
 stem:'Which client outcome statement is written correctly for the plan of care?',
 options:['"The client will feel better by discharge."','"The client will ambulate 100 feet with a walker without dizziness by postoperative day 3."','"The nurse will teach the client about wound care."','"The client will understand their medications."'],
 answer:1,
 rationale:'Outcomes must be client-centered, measurable, and time-limited. Ambulating a stated distance with a stated device by a stated day meets all three criteria. "Feel better" and "understand" are not measurable, and teaching is a nursing intervention rather than a client outcome.'},

{id:'MOC-038',cat:'MOC',b:0.95,type:'mc',
 stem:'A nurse is caring for five clients. Which finding should be reported to the practitioner immediately?',
 options:['A client with a urine output of 20 mL over the past 2 hours','A client whose incision has a small amount of serosanguineous drainage','A client with a blood glucose of 148 mg/dL 2 hours after eating','A client reporting mild nausea after receiving an opioid'],
 answer:0,
 rationale:'A urine output below roughly 0.5 mL/kg/hr signals possible acute kidney injury or hypoperfusion and must be reported promptly. Serosanguineous drainage early after surgery, a mildly elevated postprandial glucose, and mild opioid-related nausea are expected or manageable findings.'},

{id:'MOC-039',cat:'MOC',b:0.25,type:'mc',
 stem:'A nurse is reviewing the plan of care for a client with a new stroke. Which team member should the nurse consult about the client\'s difficulty swallowing?',
 options:['Physical therapist','Speech-language pathologist','Respiratory therapist','Social worker'],
 answer:1,
 rationale:'The speech-language pathologist evaluates swallowing and recommends diet texture and swallowing strategies. Physical therapy addresses mobility, respiratory therapy addresses airway and ventilation, and social work addresses discharge resources.'},

{id:'MOC-040',cat:'MOC',b:-0.1,type:'mc',
 stem:'Which nursing action best supports continuity of care for a client with multiple chronic conditions?',
 options:['Giving the client printed handouts on each condition at discharge','Scheduling separate appointments with each specialist independently','Communicating with the primary care provider and arranging a single reconciled medication list','Telling the client to call the unit with questions after discharge'],
 answer:2,
 rationale:'Continuity of care depends on shared, accurate information across providers. A reconciled medication list communicated to the primary care provider prevents duplication and interactions. Handouts alone, uncoordinated appointments, and open-ended phone offers do not close the communication loop.'}

);
