/* Additional stand-alone Next Generation NCLEX item types
   (bow-tie, drag and drop, matrix, cloze, highlight) distributed
   across the client need categories. */
(window.NCLEX_BANK = window.NCLEX_BANK || []).push(

{id:'NGN-001',cat:'PHY',b:0.55,type:'bowtie',
 scenario:'A 24-year-old client with type 1 diabetes is brought to the emergency department after 2 days of vomiting. The client is lethargic with deep, rapid respirations and a fruity breath odor. Blood glucose is 512 mg/dL, arterial pH is 7.18, serum bicarbonate is 12 mEq/L, serum potassium is 5.4 mEq/L, and serum ketones are large.',
 stem:'Complete the diagram by selecting from the choices below.',
 slots:{actions:2,params:2},
 labels:{actions:'Actions to take',condition:'Condition most likely experiencing',params:'Parameters to monitor'},
 actions:['Begin an intravenous isotonic fluid infusion',
          'Start a continuous intravenous regular insulin infusion',
          'Administer 50% dextrose intravenously',
          'Give a long-acting subcutaneous insulin dose only',
          'Withhold all fluids until the glucose normalizes'],
 conditions:['Diabetic ketoacidosis','Hyperosmolar hyperglycemic state','Hypoglycemia','Lactic acidosis from metformin'],
 params:['Serum potassium','Blood glucose hourly','Serum calcium','Urine specific gravity only'],
 answer:{actions:[0,1],condition:0,params:[0,1]},
 rationale:'Hyperglycemia with ketosis, an anion-gap acidosis, and Kussmaul respirations define diabetic ketoacidosis. Isotonic fluid replaces the profound deficit and a regular insulin infusion halts ketogenesis. Potassium must be watched closely because insulin drives potassium into cells and can cause a precipitous fall despite an initially normal or high level, and hourly glucose guides titration and the switch to dextrose-containing fluid.'},

{id:'NGN-002',cat:'RRP',b:1.15,type:'bowtie',
 scenario:'A 59-year-old client reports crushing substernal chest pressure radiating to the left jaw that began 40 minutes ago, with nausea and diaphoresis. Blood pressure is 148/90 mm Hg, heart rate is 102/min, and oxygen saturation is 94% on room air. The 12-lead electrocardiogram shows ST elevation in leads II, III, and aVF.',
 stem:'Complete the diagram by selecting from the choices below.',
 slots:{actions:2,params:2},
 labels:{actions:'Actions to take',condition:'Condition most likely experiencing',params:'Parameters to monitor'},
 actions:['Activate the cardiac catheterization team for emergent reperfusion',
          'Administer aspirin to be chewed',
          'Administer a large-volume intravenous nitroglycerin bolus without further assessment',
          'Encourage the client to walk to reproduce the pain',
          'Delay treatment until troponin results return'],
 conditions:['ST-elevation myocardial infarction of the inferior wall',
             'Stable angina','Pericarditis','Gastroesophageal reflux disease'],
 params:['Continuous cardiac rhythm','Serial troponin and pain level','Serum ammonia','Deep tendon reflexes'],
 answer:{actions:[0,1],condition:0,params:[0,1]},
 rationale:'ST elevation in the inferior leads with classic ischemic symptoms identifies an inferior ST-elevation myocardial infarction. Time to reperfusion determines survival, so the catheterization team is activated immediately and chewed aspirin is given for its rapid antiplatelet effect. Continuous rhythm monitoring detects the dysrhythmias common in inferior infarction, and serial troponins with pain assessment track the infarct and the response to treatment. Waiting for troponin results delays lifesaving reperfusion, and nitroglycerin is used cautiously in inferior infarction because of possible right ventricular involvement.'},

{id:'NGN-003',cat:'PSI',b:0.85,type:'bowtie',
 scenario:'A 31-year-old client is brought to the emergency department by police after being found shouting at people who were not present. The client has not slept in 4 days, speaks rapidly, jumps between unrelated topics, and states, "I have been chosen to rewrite the tax code." The client has a documented history of bipolar I disorder and stopped taking lithium 3 weeks ago.',
 stem:'Complete the diagram by selecting from the choices below.',
 slots:{actions:2,params:2},
 labels:{actions:'Actions to take',condition:'Condition most likely experiencing',params:'Parameters to monitor'},
 actions:['Provide a low-stimulation environment with consistent staff',
          'Offer high-calorie finger foods and fluids the client can eat while moving',
          'Confront the grandiose beliefs with logical evidence',
          'Place the client in the day room to encourage socialization',
          'Encourage a competitive group game to expend energy'],
 conditions:['Acute manic episode','Major depressive episode','Alcohol withdrawal delirium','Generalized anxiety disorder'],
 params:['Sleep pattern and duration','Nutritional and fluid intake and weight','Serum amylase','Hemoglobin A1c'],
 answer:{actions:[0,1],condition:0,params:[0,1]},
 rationale:'Decreased need for sleep, pressured speech, flight of ideas, and grandiose delusions after stopping lithium describe an acute manic episode. Reducing stimulation lowers arousal, and portable high-calorie foods meet nutritional needs in a client too active to sit for meals. Sleep and nutritional status are the parameters that show whether the episode is resolving. Arguing with delusions increases agitation, and stimulating environments and competitive activities escalate mania.'},

{id:'NGN-004',cat:'SIC',b:0.4,type:'dragdrop',
 stem:'Sort each client into the transmission-based precaution category required on admission.',
 tokens:['Active pulmonary tuberculosis','Pertussis','Clostridioides difficile colitis','Rubeola (measles)','Scabies infestation','Neisseria meningitidis meningitis'],
 buckets:['Airborne precautions','Droplet precautions','Contact precautions'],
 answer:[0,1,2,0,2,1],
 rationale:'Tuberculosis and measles spread on small airborne particles and require a negative-pressure room and a fitted respirator. Pertussis and meningococcal meningitis spread by large droplets and require a mask within about 6 feet. C. difficile and scabies spread by direct and indirect contact and require gown and gloves, with soap-and-water handwashing for C. difficile spores.'},

{id:'NGN-005',cat:'PHA',b:0.95,type:'dragdrop',
 stem:'Match each medication overdose or toxicity with its reversal agent or antidote.',
 tokens:['Warfarin','Heparin','Opioid','Benzodiazepine','Acetaminophen','Magnesium sulfate'],
 buckets:['Vitamin K','Protamine sulfate','Naloxone','Flumazenil','Acetylcysteine','Calcium gluconate'],
 answer:[0,1,2,3,4,5],
 rationale:'Each of these antidotes is specific to its agent. Confusing them is a recognized source of serious medication error, particularly the two anticoagulant reversal agents and the two central nervous system depressant antagonists.'},

{id:'NGN-006',cat:'MOC',b:0.6,type:'dragdrop',
 stem:'Sort each task according to the team member to whom it may appropriately be assigned or delegated.',
 tokens:['Perform the admission assessment on a new client',
         'Reinforce previously taught crutch-walking technique',
         'Measure and record vital signs on a stable client',
         'Develop the client plan of care',
         'Administer a scheduled oral medication to a stable client',
         'Assist a stable client with a shower'],
 buckets:['Registered nurse only','Licensed practical or vocational nurse','Unlicensed assistive personnel'],
 answer:[0,1,2,0,1,2],
 rationale:'Initial assessment and plan-of-care development require registered nurse judgment and cannot be delegated. Practical nurses reinforce established teaching and administer routine oral medications to stable clients. Assistive personnel perform standardized, predictable tasks such as vital signs on stable clients and hygiene assistance.'},

{id:'NGN-007',cat:'BCC',b:0.3,type:'dragdrop',
 stem:'Sort each food into the diet for which it is appropriate.',
 tokens:['Apple juice','Whole milk','Cream of wheat with butter','Clear beef broth','Lemon gelatin','Vanilla pudding'],
 buckets:['Clear liquid diet','Full liquid diet'],
 answer:[0,1,1,0,0,1],
 rationale:'Clear liquids are transparent at room temperature and leave minimal gastrointestinal residue: juice without pulp, broth, and gelatin. Full liquids include everything on the clear list plus opaque liquids and foods that liquefy at body temperature, such as milk, cooked refined cereal, and pudding.'},

{id:'NGN-008',cat:'PHY',b:1.05,type:'dragdrop',
 stem:'Sort each clinical finding by the type of shock it most characteristically suggests.',
 tokens:['Hives, wheezing, and hypotension after an antibiotic dose',
         'Cool clammy skin with flat neck veins after major hemorrhage',
         'Warm flushed skin with fever and a lactate of 4 mmol/L',
         'Jugular venous distention with muffled heart sounds and hypotension',
         'Bradycardia and hypotension with warm dry skin below a T4 spinal injury'],
 buckets:['Hypovolemic','Distributive','Obstructive'],
 answer:[1,0,1,2,1],
 rationale:'Anaphylactic, septic, and neurogenic shock are all distributive, caused by pathological vasodilation, though neurogenic shock is distinguished by bradycardia rather than tachycardia. Hemorrhage produces hypovolemic shock with compensatory vasoconstriction. Cardiac tamponade obstructs filling and produces obstructive shock with Beck triad.'},

{id:'NGN-009',cat:'HPM',b:0.75,type:'dragdrop',
 stem:'Sort each developmental milestone by the age at which it is typically first achieved.',
 tokens:['Sits without support','Walks independently','Speaks in two-word phrases','Rides a tricycle','Social smile'],
 buckets:['2 months','6 to 8 months','12 to 15 months','24 months','3 years'],
 answer:[1,2,3,4,0],
 rationale:'The social smile appears around 2 months, independent sitting at 6 to 8 months, independent walking at 12 to 15 months, two-word phrases near 24 months, and tricycle riding at about 3 years. Recognizing the expected sequence lets the nurse identify delay early.'},

{id:'NGN-010',cat:'RRP',b:0.7,type:'matrix',
 stem:'A client is 1 day postoperative after an open abdominal hysterectomy. For each finding, indicate whether it is expected or requires immediate follow-up.',
 rowHeader:'Finding',
 rows:['Serosanguineous drainage on the abdominal dressing',
       'Urine output of 20 mL over 2 hours',
       'Absent bowel sounds',
       'Oxygen saturation of 88% on room air',
       'Incisional pain rated 4 of 10 after analgesia',
       'Unilateral calf pain with swelling'],
 cols:['Expected','Requires immediate follow-up'],
 answer:[0,1,0,1,0,1],
 rationale:'Small amounts of serosanguineous drainage, temporarily absent bowel sounds, and moderate pain controlled by analgesia are normal on the first postoperative day. Oliguria, hypoxemia, and unilateral calf swelling suggest hypovolemia or renal hypoperfusion, atelectasis or embolism, and deep vein thrombosis, and all require prompt action.'},

{id:'NGN-011',cat:'PHA',b:1.3,type:'matrix',
 stem:'For each client situation, indicate whether the nurse should administer the medication as prescribed or hold it and notify the prescriber.',
 rowHeader:'Situation',
 rows:['Digoxin prescribed for a client with an apical rate of 52/min',
       'Metoprolol prescribed for a client with a blood pressure of 138/84 mm Hg',
       'Metformin prescribed for a client scheduled for contrast imaging today',
       'Warfarin prescribed for a client whose international normalized ratio is 6.8',
       'Enoxaparin prescribed for a client with a platelet count of 210,000/mm3'],
 cols:['Administer','Hold and notify'],
 answer:[1,0,1,1,0],
 rationale:'Digoxin is held for an apical rate below 60/min in an adult. Metformin is held around iodinated contrast because of the risk of lactic acidosis with contrast-induced renal impairment. Warfarin is held at a supratherapeutic international normalized ratio because of hemorrhage risk. The blood pressure and platelet count given are acceptable for the beta-blocker and the low-molecular-weight heparin.'},

{id:'NGN-012',cat:'PSI',b:0.5,type:'matrix',
 stem:'For each nurse statement, indicate whether it is a therapeutic or a nontherapeutic communication technique.',
 rowHeader:'Nurse statement',
 rows:['"Tell me what has been the hardest part of this week."',
       '"Everything happens for a reason."',
       '"You mentioned feeling alone. What does that look like for you?"',
       '"If I were you, I would take the surgery."',
       '"I noticed you have not eaten today."'],
 cols:['Therapeutic','Nontherapeutic'],
 answer:[0,1,0,1,0],
 rationale:'Open-ended questions, exploration of a stated feeling, and sharing an objective observation invite the client to say more. Clichés dismiss distress, and giving personal advice substitutes the nurse\'s values for the client\'s decision-making.'},

{id:'NGN-013',cat:'BCC',b:0.65,type:'cloze',
 stem:'Complete the sentences about the client\'s wound.',
 text:'A client has a pressure injury with full-thickness skin loss, visible subcutaneous fat, and no exposed bone, tendon, or muscle. The nurse should document this as a {0}. The most appropriate dressing to maintain a moist wound bed while absorbing moderate exudate is {1}.',
 blanks:[
  {options:['stage 3 pressure injury','stage 1 pressure injury','stage 2 pressure injury','stage 4 pressure injury'],answer:0},
  {options:['a foam or hydrocolloid dressing','dry gauze changed twice daily','an alcohol-soaked dressing','a dry transparent film alone'],answer:0}],
 rationale:'Stage 3 involves full-thickness loss with visible fat but without exposed bone, tendon, or muscle, which would make it stage 4. Foam and hydrocolloid dressings keep the wound bed moist while managing exudate. Dry gauze desiccates granulation tissue and alcohol is cytotoxic.'},

{id:'NGN-014',cat:'MOC',b:1.45,type:'cloze',
 stem:'Complete the sentences about prioritizing this assignment.',
 text:'A nurse receives report on four clients. The nurse should assess {0} first, because that client {1}.',
 blanks:[
  {options:['the client with new-onset confusion and an oxygen saturation of 87%',
            'the client requesting pain medication for chronic back pain',
            'the client waiting for discharge paperwork',
            'the client whose family has questions about the diet'],answer:0},
  {options:['shows signs of an acute oxygenation problem, which takes priority under airway, breathing, and circulation',
            'has been waiting the longest',
            'has the most family involvement',
            'has the most complex medication list'],answer:0}],
 rationale:'Prioritization uses airway, breathing, and circulation before comfort, discharge logistics, and teaching. New confusion with hypoxemia signals an acute, potentially reversible threat to oxygenation and must be evaluated first. Waiting time and social complexity do not establish clinical priority.'},

{id:'NGN-015',cat:'SIC',b:0.9,type:'highlight',
 stem:'The nurse observes a colleague preparing to insert an indwelling urinary catheter. Highlight each action that breaks sterile technique.',
 instr:'Tap each action that breaks sterile technique. Tap again to remove a highlight.',
 segments:['The nurse performs hand hygiene and opens the catheter kit on the overbed table.',
           'The nurse places the sterile drape and then reaches across it to adjust the bed light.',
           'The nurse dons sterile gloves without touching the outer surface.',
           'The nurse sets the sterile lubricant container near the edge of the field, half of it hanging over the side.',
           'The nurse cleanses the meatus using a new swab for each stroke, front to back.',
           'The nurse picks up a swab that fell below waist level and returns it to the field.'],
 answer:[1,3,5],
 rationale:'Reaching across a sterile field contaminates it, items must remain within the sterile boundary and not overhang the edge, and anything below waist level is considered contaminated and can never be returned to the field. Hand hygiene, correct glove technique, and front-to-back cleansing with a new swab per stroke are all correct.'},

{id:'NGN-016',cat:'PHY',b:1.2,type:'highlight',
 stem:'A client with cirrhosis is admitted. Highlight each finding that indicates decompensated liver disease.',
 instr:'Tap each finding indicating decompensation. Tap again to remove a highlight.',
 segments:['Abdominal girth has increased 8 centimeters in one week.',
           'The client is oriented to person only and has a flapping hand tremor.',
           'The client reports mild fatigue.',
           'Vomited approximately 300 mL of bright red blood this morning.',
           'Serum albumin is 2.1 g/dL and the international normalized ratio is 2.4.',
           'The client has scattered spider angiomas on the chest.'],
 answer:[0,1,3,4],
 rationale:'New ascites, hepatic encephalopathy with asterixis, variceal hemorrhage, and synthetic failure shown by low albumin with a prolonged international normalized ratio all mark decompensation and carry high short-term mortality. Fatigue is nonspecific, and spider angiomas are a chronic stigma of liver disease rather than evidence of acute decompensation.'}

);
