/* Pharmacological and Parenteral Therapies - Physiological Integrity */
(window.NCLEX_BANK = window.NCLEX_BANK || []).push(

{id:'PHA-001',cat:'PHA',b:-1.9,type:'mc',
 stem:'Before administering digoxin to an adult client, which assessment is essential?',
 options:['Apical pulse for a full minute','Blood pressure in both arms','Respiratory rate','Pupil response'],
 answer:0,
 rationale:'Digoxin slows conduction and can cause bradycardia and heart block. The apical pulse is counted for a full minute, and the dose is withheld and the prescriber notified if the rate is below 60/min in an adult.'},

{id:'PHA-002',cat:'PHA',b:-1.6,type:'mc',
 stem:'A client is prescribed 500 mg of an oral medication. The available tablets are 250 mg each. How many tablets should the nurse administer?',
 options:['0.5 tablet','1 tablet','2 tablets','4 tablets'],
 answer:2,
 rationale:'Desired dose divided by dose on hand: 500 mg divided by 250 mg per tablet equals 2 tablets.'},

{id:'PHA-003',cat:'PHA',b:-1.2,type:'mc',
 stem:'Which finding indicates that a client receiving furosemide requires immediate follow-up?',
 options:['Urine output of 1600 mL in 8 hours','Serum potassium of 2.7 mEq/L','Weight loss of 1 kilogram since yesterday','Reports of increased urination'],
 answer:1,
 rationale:'Furosemide is a potassium-wasting loop diuretic, and a potassium of 2.7 mEq/L creates a serious risk of dysrhythmia, especially in clients also taking digoxin. Increased output, diuresis, and modest weight loss are the expected therapeutic effects.'},

{id:'PHA-004',cat:'PHA',b:-0.8,type:'mc',
 stem:'A client receiving intravenous morphine has a respiratory rate of 7/min and is difficult to arouse. Which medication should the nurse anticipate administering?',
 options:['Flumazenil','Naloxone','Protamine sulfate','Acetylcysteine'],
 answer:1,
 rationale:'Naloxone is the opioid antagonist used for opioid-induced respiratory depression. Flumazenil reverses benzodiazepines, protamine reverses heparin, and acetylcysteine is the antidote for acetaminophen toxicity.'},

{id:'PHA-005',cat:'PHA',b:-0.4,type:'sata',
 stem:'A nurse is teaching a client starting warfarin. Which statements indicate correct understanding? Select all that apply.',
 options:['"I will use a soft toothbrush and an electric razor."','"I will report black tarry stools or unusual bruising."','"I can take ibuprofen for headaches."','"I will keep my international normalized ratio appointments."','"I will tell any dentist or surgeon that I take this medication."','"I will double the dose if I miss one."'],
 answer:[0,1,3,4],
 rationale:'Bleeding precautions, recognition of bleeding signs, adherence to monitoring, and informing other providers are all correct. Nonsteroidal anti-inflammatory drugs increase bleeding risk and should be avoided, and doubling a missed dose can cause hemorrhage.'},

{id:'PHA-006',cat:'PHA',b:0.1,type:'mc',
 stem:'A client is to receive heparin 25,000 units in 250 mL of dextrose 5% in water at 1000 units/hour. At what rate should the nurse set the infusion pump?',
 options:['5 mL/hour','10 mL/hour','25 mL/hour','40 mL/hour'],
 answer:1,
 rationale:'The concentration is 25,000 units divided by 250 mL, or 100 units per mL. To deliver 1000 units per hour, the rate is 1000 divided by 100, which equals 10 mL per hour.'},

{id:'PHA-007',cat:'PHA',b:0.5,type:'mc',
 stem:'A client receiving vancomycin develops flushing and a red rash over the face, neck, and upper trunk during the infusion. What is the nurse\'s priority action?',
 options:['Stop the infusion and notify the practitioner','Increase the infusion rate to finish quickly','Apply a cool cloth and continue the infusion','Administer the next dose intramuscularly'],
 answer:0,
 rationale:'This is an infusion-related histamine reaction associated with rapid administration. The infusion is stopped and the practitioner is notified; the medication is typically restarted at a slower rate with premedication. Vancomycin is not given intramuscularly.'},

{id:'PHA-008',cat:'PHA',b:0.9,type:'mc',
 stem:'A client is prescribed 0.25 mg of a medication. The vial contains 0.5 mg in 2 mL. How many milliliters should the nurse administer?',
 options:['0.5 mL','1 mL','1.5 mL','2 mL'],
 answer:1,
 rationale:'Desired over have times volume: 0.25 mg divided by 0.5 mg, multiplied by 2 mL, equals 1 mL.'},

{id:'PHA-009',cat:'PHA',b:1.3,type:'mc',
 stem:'A client weighing 70 kg is prescribed a medication at 5 mcg/kg/min. The bag contains 400 mg in 250 mL. What is the infusion rate in mL/hour?',
 options:['9.4 mL/hour','13.1 mL/hour','21 mL/hour','35 mL/hour'],
 answer:1,
 rationale:'The dose is 5 times 70, or 350 mcg/min, which is 21,000 mcg/hour, or 21 mg/hour. The concentration is 400 mg in 250 mL, or 1.6 mg/mL. Dividing 21 by 1.6 gives about 13.1 mL/hour.'},

{id:'PHA-010',cat:'PHA',b:-1.4,type:'mc',
 stem:'Which site is correct for an intramuscular injection in an adult?',
 options:['Ventrogluteal site','Dorsogluteal site','Antecubital fossa','Abdomen two inches from the umbilicus'],
 answer:0,
 rationale:'The ventrogluteal site is preferred for adult intramuscular injections because it is free of major nerves and vessels and has dense muscle. The dorsogluteal site risks sciatic nerve injury, the antecubital fossa is for venipuncture, and the abdomen is a subcutaneous site.'},

{id:'PHA-011',cat:'PHA',b:0.35,type:'mc',
 stem:'A client is receiving a unit of packed red blood cells and reports back pain, chills, and a feeling of dread 10 minutes into the infusion. What is the nurse\'s first action?',
 options:['Slow the infusion and continue monitoring','Stop the transfusion and keep the intravenous line open with normal saline','Administer an antipyretic','Obtain a urine specimen'],
 answer:1,
 rationale:'These findings suggest an acute hemolytic reaction. The transfusion is stopped immediately and the line is kept open with normal saline using new tubing. The practitioner and blood bank are notified, and the unit and a urine specimen are sent for testing.'},

{id:'PHA-012',cat:'PHA',b:0.7,type:'sata',
 stem:'Which nursing actions are correct when administering total parenteral nutrition? Select all that apply.',
 options:['Administer through a central venous access device','Monitor capillary blood glucose regularly','Abruptly discontinue the infusion when the bag is empty','Use a dedicated line or lumen for the infusion','Change the tubing and filter per policy, generally every 24 hours','Increase the rate to catch up if the infusion falls behind'],
 answer:[0,1,3,4],
 rationale:'Total parenteral nutrition is hypertonic and requires central access, a dedicated lumen, glucose monitoring, and frequent tubing changes because of infection risk. Abrupt discontinuation causes rebound hypoglycemia and the rate is tapered instead; increasing the rate to catch up causes hyperglycemia.'},

{id:'PHA-013',cat:'PHA',b:1.1,type:'mc',
 stem:'A client taking an angiotensin-converting enzyme inhibitor develops a persistent dry cough. What should the nurse do?',
 options:['Tell the client the cough is unrelated to the medication','Notify the practitioner, as the medication may need to be changed','Recommend an over-the-counter cough suppressant indefinitely','Instruct the client to stop the medication immediately'],
 answer:1,
 rationale:'A dry, nonproductive cough is a well-known effect of angiotensin-converting enzyme inhibitors caused by bradykinin accumulation. It often requires switching to an angiotensin receptor blocker. Clients should not stop antihypertensives abruptly without guidance.'},

{id:'PHA-014',cat:'PHA',b:1.6,type:'mc',
 stem:'A client receiving intravenous phenytoin has the infusion running at 75 mg/min. What should the nurse do?',
 options:['Continue, since this rate is appropriate','Slow the infusion, as the rate should not exceed 50 mg/min in adults','Increase the rate to reach a therapeutic level faster','Change the diluent to dextrose 5% in water'],
 answer:1,
 rationale:'Intravenous phenytoin must not exceed 50 mg/min in adults because faster administration causes severe hypotension and cardiac dysrhythmias. Phenytoin is incompatible with dextrose solutions and is diluted in normal saline with a filter.'},

{id:'PHA-015',cat:'PHA',b:-1.0,type:'mc',
 stem:'Which instruction should the nurse give a client prescribed an oral bisphosphonate for osteoporosis?',
 options:['"Take it at bedtime with a snack."','"Take it in the morning with a full glass of water and remain upright for at least 30 minutes."','"Take it with milk to protect your stomach."','"Lie down for an hour after taking it."'],
 answer:1,
 rationale:'Bisphosphonates cause esophageal irritation and ulceration if they lodge in the esophagus. They are taken on an empty stomach with a full glass of plain water, and the client remains upright for at least 30 minutes. Milk and other foods block absorption.'},

{id:'PHA-016',cat:'PHA',b:0.2,type:'mc',
 stem:'A nurse is preparing to give regular insulin and NPH insulin in the same syringe. Which action is correct?',
 options:['Draw up NPH first, then regular insulin','Inject air into the NPH vial, inject air into the regular vial, then draw up regular insulin followed by NPH','Draw the insulins into separate syringes and give two injections at different sites','Shake both vials vigorously before drawing up'],
 answer:1,
 rationale:'Air is injected into the cloudy NPH vial first without touching the solution, then into the clear regular vial, and the clear regular insulin is drawn up first. This prevents contaminating the short-acting vial with long-acting suspension. Insulin vials are gently rolled, never shaken.'},

{id:'PHA-017',cat:'PHA',b:0.65,type:'mc',
 stem:'A client receiving intravenous fluids has swelling, coolness, and pallor at the insertion site with a sluggish infusion. What should the nurse do first?',
 options:['Apply a warm compress and continue the infusion','Stop the infusion and remove the catheter','Flush the catheter with 10 mL of saline','Increase the infusion rate to clear the line'],
 answer:1,
 rationale:'Swelling, coolness, and pallor indicate infiltration. The infusion is stopped and the catheter removed to prevent further tissue injury. Flushing or increasing the rate forces more fluid into the tissue. Warm or cool compresses may follow depending on the solution infiltrated.'},

{id:'PHA-018',cat:'PHA',b:1.9,type:'mc',
 stem:'A client is receiving a continuous heparin infusion. The activated partial thromboplastin time is more than twice the control and the client has new bleeding from the gums. Which medication should the nurse prepare?',
 options:['Vitamin K','Protamine sulfate','Tranexamic acid','Desmopressin'],
 answer:1,
 rationale:'Protamine sulfate is the specific antidote for heparin. Vitamin K reverses warfarin. Tranexamic acid and desmopressin are used in other bleeding situations but are not the antidote for heparin.'},

{id:'PHA-019',cat:'PHA',b:-0.15,type:'sata',
 stem:'A client is prescribed a corticosteroid for long-term use. Which teaching points should the nurse include? Select all that apply.',
 options:['Never stop the medication abruptly','Report signs of infection promptly','Monitor blood glucose, as levels may rise','Expect to lose weight while taking this medication','Take with food to reduce gastric irritation','Avoid crowds and people with contagious illness'],
 answer:[0,1,2,4,5],
 rationale:'Abrupt withdrawal can cause adrenal crisis. Corticosteroids suppress immunity, raise blood glucose, and irritate the stomach. Weight gain from fluid retention and increased appetite is expected, not weight loss.'},

{id:'PHA-020',cat:'PHA',b:1.4,type:'matrix',
 stem:'For each medication, indicate the laboratory value that must be monitored most closely.',
 rowHeader:'Medication',
 rows:['Warfarin','Heparin infusion','Lithium','Vancomycin','Metformin'],
 cols:['INR/PT','aPTT','Serum drug level','Serum creatinine'],
 answer:[0,1,2,2,3],
 rationale:'Warfarin is monitored with the international normalized ratio and prothrombin time. Unfractionated heparin infusions are titrated by activated partial thromboplastin time or anti-Xa. Lithium and vancomycin require serum drug levels. Metformin requires renal function monitoring because of lactic acidosis risk when creatinine rises.'},

{id:'PHA-021',cat:'PHA',b:0.45,type:'mc',
 stem:'A client with type 1 diabetes is found diaphoretic, shaky, and confused, with a capillary blood glucose of 48 mg/dL. The client can swallow safely. What should the nurse do first?',
 options:['Administer 15 grams of a fast-acting carbohydrate','Give the scheduled dose of insulin','Start an intravenous line for dextrose 50%','Offer a high-protein snack'],
 answer:0,
 rationale:'For a conscious client who can swallow, 15 grams of fast-acting carbohydrate is given, followed by rechecking the glucose in 15 minutes. Intravenous dextrose or glucagon is reserved for clients who cannot safely swallow. Protein alone does not raise glucose quickly.'},

{id:'PHA-022',cat:'PHA',b:2.1,type:'mc',
 stem:'A client taking a selective serotonin reuptake inhibitor is started on a triptan for migraine. The client now has agitation, hyperreflexia, diaphoresis, tremor, and a temperature of 39.4 C. What does the nurse suspect?',
 options:['Neuroleptic malignant syndrome','Serotonin syndrome','Anticholinergic toxicity','Malignant hyperthermia'],
 answer:1,
 rationale:'Serotonin syndrome develops when two serotonergic agents are combined and is characterized by agitation, hyperthermia, diaphoresis, tremor, and neuromuscular hyperactivity such as hyperreflexia and clonus. Neuroleptic malignant syndrome causes lead-pipe rigidity with hyporeflexia and follows antipsychotic exposure.'},

{id:'PHA-023',cat:'PHA',b:-0.6,type:'mc',
 stem:'Which client statement indicates a need for further teaching about sublingual nitroglycerin?',
 options:['"I will sit down before taking it."','"I will call emergency services if the pain is unrelieved after the first tablet, 5 minutes apart."','"I will swallow the tablet with water."','"I will store the tablets in the original dark container."'],
 answer:2,
 rationale:'Sublingual nitroglycerin must dissolve under the tongue; swallowing destroys its effect through first-pass metabolism. Sitting prevents injury from orthostatic hypotension, emergency services are called if the first dose does not relieve pain, and the light-sensitive tablets stay in the original container.'},

{id:'PHA-024',cat:'PHA',b:1.0,type:'mc',
 stem:'A nurse is monitoring a client receiving magnesium sulfate for preeclampsia. Which finding indicates magnesium toxicity?',
 options:['Deep tendon reflexes of 2+','Urine output of 45 mL/hour','Absent patellar reflexes and a respiratory rate of 10/min','Blood pressure of 138/88 mm Hg'],
 answer:2,
 rationale:'Loss of deep tendon reflexes is the earliest sign of magnesium toxicity, followed by respiratory depression and cardiac arrest. The infusion is stopped and calcium gluconate, the antidote, is administered. Normal reflexes and adequate urine output are reassuring.'},

{id:'PHA-025',cat:'PHA',b:0.05,type:'mc',
 stem:'A client is to receive 1000 mL of normal saline over 8 hours using tubing with a drop factor of 15 gtt/mL. What is the flow rate in drops per minute?',
 options:['21 gtt/min','25 gtt/min','31 gtt/min','42 gtt/min'],
 answer:2,
 rationale:'Volume times drop factor divided by time in minutes: 1000 times 15 equals 15,000, divided by 480 minutes equals 31.25, which is rounded to 31 drops per minute.'},

{id:'PHA-026',cat:'PHA',b:1.7,type:'sata',
 stem:'A client receiving a first dose of an intravenous antibiotic develops hives, wheezing, and hypotension. Which actions should the nurse take? Select all that apply.',
 options:['Stop the antibiotic infusion immediately','Maintain the airway and administer oxygen','Prepare to administer intramuscular epinephrine','Slow the infusion and observe for 15 minutes','Establish or maintain intravenous access for fluids','Document the reaction and update the allergy record'],
 answer:[0,1,2,4,5],
 rationale:'This is anaphylaxis. The offending agent is stopped, the airway is supported, epinephrine is given intramuscularly in the anterolateral thigh, fluids are given for distributive shock, and the allergy is documented. Continuing the infusion at any rate is dangerous.'},

{id:'PHA-027',cat:'PHA',b:-1.7,type:'mc',
 stem:'Which is the correct angle for a subcutaneous injection in an average-sized adult using a 5/8-inch needle?',
 options:['15 degrees','45 to 90 degrees','90 degrees only, with the skin stretched flat','10 degrees with the bevel down'],
 answer:1,
 rationale:'Subcutaneous injections are given at 45 to 90 degrees depending on the amount of subcutaneous tissue and the needle length. A 15-degree angle with the bevel up is used for intradermal injections.'},

{id:'PHA-028',cat:'PHA',b:0.85,type:'mc',
 stem:'A client on a patient-controlled analgesia pump is difficult to arouse with a respiratory rate of 8/min. Which action should the nurse take first?',
 options:['Stop the patient-controlled analgesia infusion and stimulate the client','Ask a family member to press the button for the client','Increase the lockout interval','Document the finding and reassess in 1 hour'],
 answer:0,
 rationale:'Stopping the opioid and arousing the client are the immediate priorities, followed by oxygen, notification, and preparation for naloxone. Family members must never press the button, which is a key safety feature of patient-controlled analgesia.'},

{id:'PHA-029',cat:'PHA',b:0.3,type:'mc',
 stem:'A client is prescribed levothyroxine. Which teaching point is correct?',
 options:['"Take it with breakfast and your calcium supplement."','"Take it on an empty stomach in the morning, separated from calcium and iron by at least 4 hours."','"Stop the medication when you feel better."','"Expect your heart rate to slow considerably."'],
 answer:1,
 rationale:'Levothyroxine absorption is markedly reduced by food and by calcium and iron products, so it is taken on an empty stomach with separation from those supplements. It is a lifelong replacement therapy, and excessive dosing produces tachycardia rather than bradycardia.'},

{id:'PHA-030',cat:'PHA',b:1.25,type:'cloze',
 stem:'Complete the sentences about the client\'s insulin therapy.',
 text:'A client receives regular insulin subcutaneously at 0730. The nurse should watch most closely for hypoglycemia at approximately {0}, because the peak action of regular insulin occurs about {1} after administration.',
 blanks:[
  {options:['1000 to 1130','0745 to 0800','1600 to 1800','2200 to 2400'],answer:0},
  {options:['2 to 4 hours','15 minutes','12 hours','24 hours'],answer:0}],
 rationale:'Short-acting regular insulin begins working in about 30 minutes, peaks at roughly 2 to 4 hours, and lasts 5 to 8 hours. A 0730 dose therefore peaks in the late morning, which is when hypoglycemia is most likely.'},

{id:'PHA-031',cat:'PHA',b:-0.25,type:'mc',
 stem:'Which nursing action is correct before administering a first dose of an antibiotic?',
 options:['Obtain ordered culture specimens before the first dose','Administer the antibiotic and then collect cultures','Skip cultures if the client already has a fever','Delay the antibiotic until culture results return'],
 answer:0,
 rationale:'Cultures are obtained before the first antibiotic dose so that the causative organism can still be recovered, but antibiotic administration must not be delayed waiting for results in a client with suspected sepsis.'},

{id:'PHA-032',cat:'PHA',b:1.5,type:'mc',
 stem:'A client taking an antipsychotic develops a temperature of 40 C, severe muscle rigidity, altered consciousness, and an elevated creatine kinase. What should the nurse anticipate?',
 options:['Continuing the antipsychotic and adding an anticholinergic','Discontinuing the antipsychotic and initiating cooling and supportive care','Administering an additional dose of the antipsychotic','Providing reassurance that this is an expected effect'],
 answer:1,
 rationale:'These findings describe neuroleptic malignant syndrome, a life-threatening reaction requiring immediate discontinuation of the antipsychotic, aggressive cooling, hydration, and often dantrolene or bromocriptine. Continuing the drug is fatal.'},

{id:'PHA-033',cat:'PHA',b:-1.1,type:'mc',
 stem:'Which of the "rights" of medication administration does the nurse address by comparing the medication label to the medication administration record three times?',
 options:['Right client','Right drug','Right to refuse','Right documentation'],
 answer:1,
 rationale:'The three checks of the label against the medication administration record, performed when retrieving, preparing, and administering, verify that the correct drug is being given. Client identity is verified separately using two identifiers.'},

{id:'PHA-034',cat:'PHA',b:0.55,type:'mc',
 stem:'A client with chronic pain is prescribed a long-acting opioid every 12 hours plus a short-acting opioid as needed. The client asks why both are needed. What is the nurse\'s best response?',
 options:['"The long-acting drug provides a steady baseline and the short-acting drug treats breakthrough pain."','"Taking two opioids reduces the risk of addiction."','"The short-acting drug is a placebo."','"You should choose one and stop the other."'],
 answer:0,
 rationale:'Around-the-clock long-acting analgesia maintains a stable serum level, while a short-acting agent is added for breakthrough pain. This is a standard approach to chronic pain and does not by itself constitute misuse.'},

{id:'PHA-035',cat:'PHA',b:1.05,type:'mc',
 stem:'A client is receiving intravenous potassium chloride 20 mEq in 100 mL over 1 hour through a peripheral line and reports burning at the site. What should the nurse do first?',
 options:['Stop the infusion and assess the site','Apply heat and continue at the same rate','Increase the rate to shorten the exposure','Administer an analgesic and continue'],
 answer:0,
 rationale:'Burning suggests phlebitis or infiltration from this irritating solution. The infusion is stopped and the site assessed. Options include slowing the rate, further dilution, or a central line. Speeding the infusion of potassium is dangerous and can be fatal.'},

{id:'PHA-036',cat:'PHA',b:-0.45,type:'mc',
 stem:'A client is prescribed an inhaled corticosteroid and a short-acting beta-2 agonist. Which instruction should the nurse give about the order of use?',
 options:['Use the corticosteroid first, then the bronchodilator','Use the bronchodilator first, wait a few minutes, then use the corticosteroid, and rinse the mouth afterward','Use them at the same time','Use only the corticosteroid during an acute attack'],
 answer:1,
 rationale:'The bronchodilator opens the airways so the corticosteroid can be deposited more deeply. Rinsing the mouth after the corticosteroid prevents oral candidiasis. Inhaled corticosteroids are controllers and do not relieve acute bronchospasm.'}

);
