/* Physiological Adaptation - Physiological Integrity */
(window.NCLEX_BANK = window.NCLEX_BANK || []).push(

{id:'PHY-001',cat:'PHY',b:-1.9,type:'mc',
 stem:'A client with chronic obstructive pulmonary disease has a room air oxygen saturation of 89%. Which finding should the nurse expect on assessment?',
 options:['Barrel chest with prolonged expiration','Bounding peripheral pulses with warm extremities','A wide pulse pressure with a hyperdynamic precordium','Loud, high-pitched inspiratory stridor'],
 answer:0,
 rationale:'Air trapping in chronic obstructive pulmonary disease produces an increased anteroposterior chest diameter and a prolonged expiratory phase, often with pursed-lip breathing. Stridor indicates upper airway obstruction, not lower airway disease.'},

{id:'PHY-002',cat:'PHY',b:-1.5,type:'mc',
 stem:'A client is admitted with dehydration. Which finding supports this diagnosis?',
 options:['Bounding pulse and distended neck veins','Urine specific gravity of 1.035 and dry mucous membranes','Crackles in the lung bases','Weight gain of 2 kilograms in 24 hours'],
 answer:1,
 rationale:'Concentrated urine with a high specific gravity, dry mucous membranes, poor skin turgor, tachycardia, and weight loss reflect fluid volume deficit. Distended neck veins, crackles, and rapid weight gain indicate fluid overload.'},

{id:'PHY-003',cat:'PHY',b:-1.0,type:'mc',
 stem:'A client with heart failure gains 1.4 kilograms overnight. What does this most likely represent?',
 options:['Approximately 1400 mL of retained fluid','Increased muscle mass','Improved nutritional status','Measurement error only'],
 answer:0,
 rationale:'One kilogram of acute weight change corresponds to about 1 liter of fluid, so a 1.4-kilogram overnight gain represents roughly 1400 mL of retained fluid and is an early sign of worsening heart failure.'},

{id:'PHY-004',cat:'PHY',b:-0.6,type:'sata',
 stem:'Which findings would the nurse expect in a client with hypokalemia? Select all that apply.',
 options:['Muscle weakness and leg cramps','Flattened T waves with prominent U waves','Peaked T waves','Decreased bowel sounds and abdominal distention','Hyperactive deep tendon reflexes','Increased risk of digoxin toxicity'],
 answer:[0,1,3,5],
 rationale:'Low potassium reduces neuromuscular and smooth muscle excitability, producing weakness, cramps, and ileus, and it produces flattened T waves with U waves. It also potentiates digoxin toxicity. Peaked T waves and hyperreflexia are seen with hyperkalemia.'},

{id:'PHY-005',cat:'PHY',b:-0.2,type:'mc',
 stem:'A client with cirrhosis has increasing confusion and asterixis. Which laboratory value best explains these findings?',
 options:['Elevated serum ammonia','Elevated hemoglobin','Decreased white blood cell count','Elevated serum sodium'],
 answer:0,
 rationale:'Hepatic encephalopathy results from the failing liver\'s inability to convert ammonia to urea. Rising ammonia produces confusion, asterixis, and eventually coma. Lactulose and rifaximin are used to reduce ammonia production and absorption.'},

{id:'PHY-006',cat:'PHY',b:0.25,type:'mc',
 stem:'A client with diabetes has a blood glucose of 620 mg/dL, Kussmaul respirations, and a fruity breath odor. Which intervention should the nurse anticipate first?',
 options:['Intravenous regular insulin bolus followed by an infusion','Intravenous isotonic fluid resuscitation','Sodium bicarbonate administration','Oral hypoglycemic agents'],
 answer:1,
 rationale:'In diabetic ketoacidosis, profound volume depletion is the immediate threat, so isotonic fluid replacement begins first, followed closely by an insulin infusion and potassium replacement. Bicarbonate is reserved for severe acidosis, and oral agents have no role.'},

{id:'PHY-007',cat:'PHY',b:0.7,type:'mc',
 stem:'A client with a history of Addison disease is admitted with hypotension, weakness, hyperkalemia, and hyponatremia after an illness. Which treatment should the nurse anticipate?',
 options:['Intravenous hydrocortisone and isotonic fluids','Intravenous insulin and glucose only','Diuretic therapy','Potassium supplementation'],
 answer:0,
 rationale:'This is an adrenal crisis caused by acute cortisol deficiency, often precipitated by stress or illness. Immediate glucocorticoid replacement and aggressive isotonic fluid resuscitation are lifesaving. Adding potassium or a diuretic would worsen the electrolyte picture.'},

{id:'PHY-008',cat:'PHY',b:1.1,type:'mc',
 stem:'A client with a spinal cord injury at T4 develops a pounding headache, blood pressure of 210/110 mm Hg, flushing above the injury, and sweating. What should the nurse do first?',
 options:['Place the client in a sitting position and look for the triggering stimulus','Administer an analgesic for the headache','Lay the client flat and elevate the legs','Restrict fluids'],
 answer:0,
 rationale:'This is autonomic dysreflexia, a medical emergency in injuries at or above T6. Sitting the client upright lowers blood pressure immediately, and the nurse then removes the noxious stimulus, most often a distended bladder or impacted bowel. Lying flat worsens the hypertension.'},

{id:'PHY-009',cat:'PHY',b:1.5,type:'mc',
 stem:'A client is admitted with a suspected acute ischemic stroke, with symptom onset 90 minutes ago. Which action should the nurse anticipate first?',
 options:['Administer aspirin immediately','Obtain a noncontrast computed tomography scan of the head','Start anticoagulation with heparin','Begin physical therapy'],
 answer:1,
 rationale:'A noncontrast head computed tomography scan must exclude hemorrhage before thrombolytic therapy can be considered within the treatment window. Giving aspirin or an anticoagulant before imaging could be fatal in a hemorrhagic stroke.'},

{id:'PHY-010',cat:'PHY',b:-1.3,type:'mc',
 stem:'Which finding indicates that a client is developing fluid volume overload?',
 options:['Jugular venous distention and bibasilar crackles','Flat neck veins and orthostatic hypotension','Urine specific gravity of 1.032','Poor skin turgor'],
 answer:0,
 rationale:'Jugular venous distention, crackles, dependent edema, bounding pulses, and rapid weight gain reflect excess volume. Flat neck veins, orthostasis, concentrated urine, and poor turgor indicate deficit.'},

{id:'PHY-011',cat:'PHY',b:0.45,type:'sata',
 stem:'A client is admitted with sepsis. Which findings support this diagnosis? Select all that apply.',
 options:['Temperature of 35.2 C','Heart rate of 122/min','Serum lactate of 4.2 mmol/L','Mean arterial pressure of 58 mm Hg','Serum sodium of 140 mEq/L','Altered mental status'],
 answer:[0,1,2,3,5],
 rationale:'Sepsis can present with hypothermia as well as fever. Tachycardia, elevated lactate reflecting tissue hypoperfusion, hypotension, and altered mentation are all consistent. A normal sodium level neither supports nor refutes the diagnosis.'},

{id:'PHY-012',cat:'PHY',b:0.95,type:'ordered',
 stem:'A client on a medical unit is found unresponsive without a pulse. Place the nurse\'s actions in the correct order.',
 options:['Check responsiveness and call for help and the code team','Check for a pulse and breathing for no more than 10 seconds','Begin high-quality chest compressions','Attach the automated external defibrillator or monitor and analyze the rhythm','Defibrillate if a shockable rhythm is present'],
 rationale:'The sequence is to establish unresponsiveness and summon help and the defibrillator, briefly confirm pulselessness, start compressions immediately, then apply the defibrillator and shock a shockable rhythm. Early compressions and early defibrillation drive survival.'},

{id:'PHY-013',cat:'PHY',b:1.35,type:'bowtie',
 stem:'A 68-year-old client with heart failure presents with worsening dyspnea and a 3-kilogram weight gain over 2 days. Vital signs are blood pressure 154/92 mm Hg, heart rate 108/min, respiratory rate 28/min, and oxygen saturation 88% on room air. Auscultation reveals bibasilar crackles, and the client has 2+ pitting edema and jugular venous distention.',
 instr:'Complete the diagram by selecting the condition the client is most likely experiencing, two actions to take, and two parameters to monitor.',
 slots:{actions:2,params:2},
 labels:{actions:'Actions to take',condition:'Condition most likely experiencing',params:'Parameters to monitor'},
 actions:['Place the client in high Fowler position and apply oxygen',
          'Administer the prescribed intravenous loop diuretic',
          'Administer a 1000 mL normal saline bolus',
          'Encourage increased oral fluid intake',
          'Place the client flat to improve venous return'],
 conditions:['Acute decompensated heart failure with pulmonary congestion',
             'Hypovolemic shock',
             'Diabetic ketoacidosis',
             'Acute pancreatitis'],
 params:['Daily weight and strict intake and output',
         'Oxygen saturation and respiratory effort',
         'Serum amylase and lipase',
         'Stool frequency and consistency'],
 answer:{actions:[0,1],condition:0,params:[0,1]},
 rationale:'Rapid weight gain, crackles, jugular venous distention, edema, and hypoxemia describe acute decompensated heart failure with pulmonary congestion. Upright positioning with oxygen improves ventilation immediately, and a loop diuretic removes the excess volume. Daily weight with intake and output tracks fluid removal, and oxygen saturation with respiratory effort tracks the pulmonary response. Fluid boluses, increased oral fluids, and lying flat all worsen congestion.'},

{id:'PHY-014',cat:'PHY',b:-0.85,type:'mc',
 stem:'A client with a history of asthma is wheezing audibly, using accessory muscles, and can speak only in single words. Which action is the priority?',
 options:['Administer the prescribed short-acting bronchodilator by nebulizer and apply oxygen','Obtain peak flow measurements every 15 minutes','Teach pursed-lip breathing technique','Draw blood for an arterial blood gas'],
 answer:0,
 rationale:'Severe bronchospasm with single-word dyspnea is a respiratory emergency requiring immediate bronchodilation and oxygen. Diagnostic measures and teaching follow stabilization.'},

{id:'PHY-015',cat:'PHY',b:0.15,type:'mc',
 stem:'A client with end-stage kidney disease misses a dialysis session. Which finding requires the most immediate action?',
 options:['Serum potassium of 6.9 mEq/L','Serum creatinine of 8 mg/dL','Blood urea nitrogen of 60 mg/dL','Weight gain of 2 kilograms'],
 answer:0,
 rationale:'Hyperkalemia is the most immediately life-threatening complication of missed dialysis because it can cause fatal dysrhythmia. Elevated creatinine, urea, and interdialytic weight gain are expected and are corrected by the next treatment.'},

{id:'PHY-016',cat:'PHY',b:1.75,type:'mc',
 stem:'A client with a chest injury has tracheal deviation to the left, absent breath sounds on the right, distended neck veins, and hypotension. What should the nurse anticipate?',
 options:['Immediate needle decompression of the right chest','Administration of a bronchodilator','Placement in Trendelenburg','A 12-lead electrocardiogram before any intervention'],
 answer:0,
 rationale:'These findings describe a tension pneumothorax, in which trapped air collapses the lung and shifts the mediastinum, obstructing venous return. Immediate needle decompression followed by chest tube placement is lifesaving; delays for diagnostics are fatal.'},

{id:'PHY-017',cat:'PHY',b:-0.4,type:'mc',
 stem:'A client with hypocalcemia is being monitored after a thyroidectomy. Which assessment finding should the nurse expect?',
 options:['Positive Chvostek and Trousseau signs','Constipation and lethargy','Bone pain and kidney stones','Decreased deep tendon reflexes'],
 answer:0,
 rationale:'Low calcium increases neuromuscular excitability, producing facial twitching when the facial nerve is tapped (Chvostek sign) and carpal spasm with blood pressure cuff inflation (Trousseau sign). Constipation, lethargy, bone pain, and stones are features of hypercalcemia.'},

{id:'PHY-018',cat:'PHY',b:0.6,type:'matrix',
 stem:'For each clinical finding, indicate the acid-base disturbance it most likely reflects.',
 rowHeader:'Clinical situation',
 rows:['Prolonged vomiting with gastric fluid loss',
       'Severe diarrhea with bicarbonate loss',
       'Opioid overdose with hypoventilation',
       'Acute anxiety with rapid deep breathing'],
 cols:['Metabolic acidosis','Metabolic alkalosis','Respiratory acidosis','Respiratory alkalosis'],
 answer:[1,0,2,3],
 rationale:'Vomiting removes hydrochloric acid and causes metabolic alkalosis. Diarrhea removes bicarbonate and causes metabolic acidosis. Hypoventilation retains carbon dioxide and causes respiratory acidosis. Hyperventilation eliminates carbon dioxide and causes respiratory alkalosis.'},

{id:'PHY-019',cat:'PHY',b:1.2,type:'mc',
 stem:'A client with a new ileostomy has had 1800 mL of watery output in 8 hours. Which complication should the nurse assess for first?',
 options:['Fluid and electrolyte imbalance','Constipation','Weight gain','Hypertension'],
 answer:0,
 rationale:'High ileostomy output causes rapid loss of water, sodium, and potassium, producing dehydration and electrolyte imbalance. The nurse monitors intake and output, weight, and electrolytes and anticipates fluid replacement.'},

{id:'PHY-020',cat:'PHY',b:-1.15,type:'mc',
 stem:'A client is having a generalized tonic-clonic seizure. What should the nurse do?',
 options:['Insert a padded tongue blade between the teeth','Turn the client to the side, protect the head, and time the seizure','Restrain the extremities to prevent injury','Leave to find another staff member'],
 answer:1,
 rationale:'Side-lying positioning protects the airway from secretions, padding and clearing the area prevents injury, and timing guides treatment decisions. Nothing is placed in the mouth, extremities are never restrained, and the client is not left alone.'},

{id:'PHY-021',cat:'PHY',b:0.35,type:'mc',
 stem:'A client with peripheral arterial disease reports leg pain when walking that resolves with rest. Which teaching is most appropriate?',
 options:['"Elevate your legs above your heart when they hurt."','"Walk to the point of discomfort, rest, then continue, and keep your legs in a dependent position for comfort."','"Apply a heating pad directly to your feet."','"Wear compression stockings during the day."'],
 answer:1,
 rationale:'Intermittent claudication improves with a graded walking program that promotes collateral circulation, and dependent positioning uses gravity to aid arterial flow. Elevation and compression reduce arterial perfusion, and direct heat risks burns in a limb with impaired sensation and perfusion.'},

{id:'PHY-022',cat:'PHY',b:1.6,type:'mc',
 stem:'A client with severe burns to 45% of the body surface is 6 hours postinjury. Which finding indicates adequate fluid resuscitation?',
 options:['Urine output of 0.5 to 1 mL/kg/hour','Heart rate of 140/min','Urine output of 10 mL/hour','Hematocrit that continues to rise'],
 answer:0,
 rationale:'Urine output of about 0.5 mL/kg/hour in adults is the primary indicator of adequate resuscitation during the emergent burn phase. Persistent tachycardia, oliguria, and a rising hematocrit from hemoconcentration all indicate continued hypovolemia.'},

{id:'PHY-023',cat:'PHY',b:-0.05,type:'mc',
 stem:'A client with hypothyroidism is admitted with hypothermia, bradycardia, and decreasing level of consciousness. What condition should the nurse suspect?',
 options:['Myxedema coma','Thyroid storm','Hyperosmolar hyperglycemic state','Adrenal crisis'],
 answer:0,
 rationale:'Myxedema coma is decompensated hypothyroidism marked by hypothermia, bradycardia, hypoventilation, hyponatremia, and depressed consciousness. Thyroid storm presents with the opposite picture of fever, tachycardia, and agitation.'},

{id:'PHY-024',cat:'PHY',b:0.85,type:'mc',
 stem:'A client with a bowel obstruction has abdominal distention, vomiting, and absent bowel sounds. Which nursing intervention should the nurse anticipate?',
 options:['Insert a nasogastric tube for decompression and keep the client nothing by mouth','Administer a bulk-forming laxative','Give a full liquid diet','Encourage ambulation with oral fluids'],
 answer:0,
 rationale:'Gastric decompression relieves distention, prevents vomiting and aspiration, and reduces pressure on the bowel wall while the client is kept nothing by mouth and given intravenous fluids. Laxatives and oral intake worsen an obstruction.'},

{id:'PHY-025',cat:'PHY',b:1.9,type:'mc',
 stem:'A client receiving chemotherapy has a white blood cell count of 1200/mm3 with an absolute neutrophil count of 400/mm3 and a temperature of 38.4 C. What is the priority action?',
 options:['Administer an antipyretic and reassess in 1 hour','Obtain cultures and initiate broad-spectrum antibiotics urgently as prescribed','Encourage oral fluids and rest','Apply a cooling blanket'],
 answer:1,
 rationale:'Neutropenic fever is an oncologic emergency. Because the client cannot mount a normal inflammatory response, a single temperature elevation may be the only sign of overwhelming infection. Cultures are drawn and empiric antibiotics started within about an hour.'},

{id:'PHY-026',cat:'PHY',b:-0.75,type:'mc',
 stem:'A client with gastroesophageal reflux disease asks how to reduce nighttime symptoms. Which instruction is correct?',
 options:['"Eat a large meal before bed so your stomach is not empty."','"Elevate the head of your bed and avoid eating for 3 hours before lying down."','"Lie flat immediately after eating to aid digestion."','"Drink peppermint tea at bedtime."'],
 answer:1,
 rationale:'Gravity reduces reflux, so elevating the head of the bed and allowing the stomach to empty before reclining are the core measures. Large late meals, recumbency after eating, and peppermint, which relaxes the lower esophageal sphincter, all worsen reflux.'},

{id:'PHY-027',cat:'PHY',b:0.5,type:'mc',
 stem:'A client is admitted with syndrome of inappropriate antidiuretic hormone. Which nursing intervention should the nurse anticipate?',
 options:['Fluid restriction','Administration of desmopressin','Free water boluses through a feeding tube','Encouraging fluids to 3 liters per day'],
 answer:0,
 rationale:'Excess antidiuretic hormone causes water retention with dilutional hyponatremia, so treatment centers on restricting fluids and correcting sodium slowly to avoid osmotic demyelination. Desmopressin and additional free water treat diabetes insipidus, the opposite disorder.'},

{id:'PHY-028',cat:'PHY',b:1.45,type:'mc',
 stem:'A client with a history of atrial fibrillation suddenly develops severe abdominal pain out of proportion to the physical examination, with a soft abdomen. What complication should the nurse suspect?',
 options:['Acute mesenteric ischemia from an embolus','Simple constipation','Gastroesophageal reflux','Irritable bowel syndrome'],
 answer:0,
 rationale:'Pain out of proportion to examination findings in a client with atrial fibrillation strongly suggests embolic mesenteric ischemia, a surgical emergency. Delay leads to bowel infarction, and mortality rises sharply with time.'},

{id:'PHY-029',cat:'PHY',b:-1.45,type:'mc',
 stem:'Which position should the nurse use for a client with increased intracranial pressure?',
 options:['Head of the bed elevated 30 degrees with the head midline','Trendelenburg','Prone with the neck rotated','Flat with the hips flexed'],
 answer:0,
 rationale:'Elevating the head about 30 degrees with the head and neck in neutral alignment promotes venous drainage from the brain. Trendelenburg, neck rotation, and hip flexion all impede venous outflow and raise intracranial pressure.'},

{id:'PHY-030',cat:'PHY',b:0.75,type:'cloze',
 stem:'Complete the sentences about the client\'s condition.',
 text:'A client presents with polyuria, polydipsia, a serum glucose of 980 mg/dL, a serum osmolality of 340 mOsm/kg, and no ketones. The client is most likely experiencing {0}, and the priority initial treatment is {1}.',
 blanks:[
  {options:['hyperosmolar hyperglycemic state','diabetic ketoacidosis','hypoglycemia','diabetes insipidus'],answer:0},
  {options:['aggressive intravenous isotonic fluid replacement','a subcutaneous rapid-acting insulin dose only','oral carbohydrate replacement','fluid restriction'],answer:0}],
 rationale:'Extreme hyperglycemia with high osmolality and no ketosis characterizes hyperosmolar hyperglycemic state, which occurs when enough insulin remains to prevent ketogenesis. Profound dehydration is the immediate threat, so isotonic fluid resuscitation precedes and accompanies an insulin infusion.'},

{id:'PHY-031',cat:'PHY',b:0.05,type:'mc',
 stem:'A client with anemia has a hemoglobin of 7.1 g/dL. Which assessment finding should the nurse expect?',
 options:['Fatigue, pallor, and exertional dyspnea','Polycythemia and flushed skin','Bradycardia and hypertension','Increased exercise tolerance'],
 answer:0,
 rationale:'Reduced oxygen-carrying capacity produces fatigue, pallor, tachycardia, and dyspnea on exertion as the body attempts to compensate. Bradycardia and increased exercise tolerance are inconsistent with significant anemia.'},

{id:'PHY-032',cat:'PHY',b:1.05,type:'sata',
 stem:'A client is admitted with acute pancreatitis. Which interventions should the nurse anticipate? Select all that apply.',
 options:['Keep the client nothing by mouth initially','Administer prescribed analgesia','Provide a high-fat diet to maintain calories','Monitor serum calcium and glucose','Position the client sitting up and leaning forward for comfort','Administer intravenous fluids for volume replacement'],
 answer:[0,1,3,4,5],
 rationale:'Resting the pancreas by withholding oral intake, controlling pain, aggressive fluid replacement, and monitoring for hypocalcemia and hyperglycemia are standard. A knee-to-chest or forward-leaning position eases pain. Fat stimulates pancreatic enzyme secretion and worsens the inflammation.'}

);
