/* Psychosocial Integrity */
(window.NCLEX_BANK = window.NCLEX_BANK || []).push(

{id:'PSI-001',cat:'PSI',b:-1.8,type:'mc',
 stem:'A client says, "I do not think I will ever get better." Which response by the nurse is therapeutic?',
 options:['"Of course you will get better. Do not talk like that."','"You sound discouraged. Tell me more about what you are feeling."','"Everyone feels that way sometimes."','"Let me get you something to help you relax."'],
 answer:1,
 rationale:'Reflecting the feeling and inviting the client to say more keeps the conversation open and communicates that the nurse is listening. False reassurance, minimizing with generalizations, and offering medication all shut down expression of feelings.'},

{id:'PSI-002',cat:'PSI',b:-1.2,type:'mc',
 stem:'A client with severe anxiety is pacing and speaking rapidly. What is the nurse\'s priority intervention?',
 options:['Ask the client to complete an anxiety questionnaire','Remain with the client and speak calmly in short, simple sentences','Encourage the client to attend the group activity','Explain the physiology of the anxiety response'],
 answer:1,
 rationale:'Severe anxiety narrows perception and impairs learning, so the nurse stays with the client, provides a calm presence, and uses short, simple, directive statements. Complex tasks, group stimulation, and teaching are ineffective until anxiety decreases to a mild or moderate level.'},

{id:'PSI-003',cat:'PSI',b:-0.7,type:'mc',
 stem:'A client with schizophrenia says, "The voices are telling me I am worthless." Which response is most appropriate?',
 options:['"There are no voices. You are safe here."','"What are the voices saying to you? Are they telling you to hurt yourself or anyone else?"','"Try to ignore the voices and watch television."','"Why do you think the voices say that?"'],
 answer:1,
 rationale:'The priority is safety, so the nurse assesses the content of the hallucination for command messages to harm self or others. The nurse neither argues about nor validates the reality of the voices. "Why" questions are challenging and rarely productive.'},

{id:'PSI-004',cat:'PSI',b:0.1,type:'mc',
 stem:'A client is admitted after a suicide attempt. Which nursing action is the priority?',
 options:['Establish a no-suicide contract','Remove potentially harmful objects and provide the level of observation ordered','Explore the client\'s childhood experiences','Encourage the client to participate in unit activities'],
 answer:1,
 rationale:'Environmental safety and appropriate observation are the priority because they directly reduce the means and opportunity for self-harm. No-harm contracts have not been shown to prevent suicide, and exploration and activity come after safety is secured.'},

{id:'PSI-005',cat:'PSI',b:0.6,type:'sata',
 stem:'Which findings would lead the nurse to suspect that an older adult client is experiencing neglect? Select all that apply.',
 options:['Severe dehydration with an unexplained 15-pound weight loss','Untreated pressure injuries with a strong odor','A caregiver who answers all questions and will not leave the client alone with staff','Prescriptions that are consistently unfilled','A neatly groomed appearance with clean clothing','Multiple missed medical appointments'],
 answer:[0,1,2,3,5],
 rationale:'Neglect is suggested by unmet basic needs such as dehydration, weight loss, untreated wounds, unfilled prescriptions, and missed appointments, and by a controlling caregiver who prevents private interviews. Good grooming does not by itself suggest neglect.'},

{id:'PSI-006',cat:'PSI',b:1.0,type:'mc',
 stem:'A client experiencing alcohol withdrawal 36 hours after the last drink has tremors, diaphoresis, blood pressure 168/96 mm Hg, and heart rate 118/min. Which finding indicates the withdrawal is becoming life-threatening?',
 options:['Nausea relieved by an antiemetic','A single episode of vomiting','A generalized tonic-clonic seizure','Difficulty sleeping'],
 answer:2,
 rationale:'Withdrawal seizures and delirium tremens mark severe, potentially fatal withdrawal. They require immediate treatment, usually with benzodiazepines and close monitoring. Nausea, vomiting, and insomnia are common but not life-threatening in themselves.'},

{id:'PSI-007',cat:'PSI',b:-0.4,type:'mc',
 stem:'A client whose spouse died 3 weeks ago says, "I keep setting the table for two." Which response is most therapeutic?',
 options:['"You need to accept that your spouse is gone."','"That must be painful. Habits from a shared life can be hard to change."','"You should put away the extra dishes."','"It is time to focus on the future."'],
 answer:1,
 rationale:'Acknowledging the pain and normalizing the experience supports grief work. Directing the client to accept the loss, change behaviors, or move on dismisses the feelings and interferes with healthy mourning.'},

{id:'PSI-008',cat:'PSI',b:1.4,type:'mc',
 stem:'A client with borderline personality disorder tells the nurse, "You are the only one here who really understands me. The other nurses are terrible." What is the best response?',
 options:['"Thank you. I do try harder than the others."','"All of the nurses here want to help you. Let us talk about what happened with the other nurse."','"You should not speak about your other nurses that way."','"I will ask to be your only nurse from now on."'],
 answer:1,
 rationale:'This is splitting, a defense that divides staff into all-good and all-bad. The nurse maintains a consistent team message, avoids accepting the flattery, and redirects the client to the actual concern. Agreeing or scolding both reinforce the pattern.'},

{id:'PSI-009',cat:'PSI',b:0.3,type:'mc',
 stem:'A nurse is caring for a client from a culture in which direct eye contact with authority figures is considered disrespectful. The client looks down during the interview. What should the nurse do?',
 options:['Ask the client to look at the nurse while speaking','Continue the interview and interpret the behavior in its cultural context','Document that the client is depressed','Assume that the client does not understand English'],
 answer:1,
 rationale:'Avoiding eye contact is a culturally normative behavior in many groups and must not be interpreted as depression, dishonesty, or poor comprehension. The nurse adapts to the client\'s communication norms rather than requiring conformity.'},

{id:'PSI-010',cat:'PSI',b:-0.9,type:'mc',
 stem:'A client is admitted to a psychiatric unit voluntarily and now requests discharge. What is the nurse\'s correct action?',
 options:['Tell the client they must stay for the full treatment program','Notify the practitioner of the request, as the client generally has the right to leave','Place the client on involuntary hold immediately','Ask the family to convince the client to stay'],
 answer:1,
 rationale:'Voluntary clients retain the right to request discharge, usually after a written request and a defined notice period. The nurse notifies the practitioner, who evaluates whether the client meets criteria for involuntary commitment; only then can discharge be denied.'},

{id:'PSI-011',cat:'PSI',b:1.7,type:'mc',
 stem:'A client with anorexia nervosa is admitted with a body mass index of 14 and a potassium level of 2.8 mEq/L. Which nursing intervention takes priority?',
 options:['Exploring the client\'s body image concerns','Monitoring cardiac rhythm and electrolyte replacement during refeeding','Establishing a behavioral contract for weight gain','Encouraging the client to journal about meals'],
 answer:1,
 rationale:'Severe malnutrition with hypokalemia creates immediate risk of fatal dysrhythmia, and refeeding syndrome can worsen electrolyte shifts. Physiological stabilization with cardiac and electrolyte monitoring precedes psychotherapeutic work.'},

{id:'PSI-012',cat:'PSI',b:0.8,type:'sata',
 stem:'Which nursing actions are appropriate when caring for a client experiencing delirium? Select all that apply.',
 options:['Reorient the client frequently using a clock and calendar','Keep the room brightly lit and noisy at night to prevent sleep','Involve family members in providing familiar reassurance','Identify and treat underlying causes such as infection or medication effects','Restrain the client early to prevent agitation','Maintain consistent staff assignment when possible'],
 answer:[0,2,3,5],
 rationale:'Delirium management centers on identifying reversible causes and reducing confusion through orientation cues, familiar people, and consistency. Night-time stimulation worsens sleep-wake disruption, and restraints increase agitation and injury and are a last resort.'},

{id:'PSI-013',cat:'PSI',b:-1.4,type:'mc',
 stem:'Which statement by the nurse is an example of a nontherapeutic communication technique?',
 options:['"Tell me more about that."','"Why did you stop taking your medication?"','"You seem upset today."','"I will stay here with you."'],
 answer:1,
 rationale:'"Why" questions demand justification and put the client on the defensive. Open-ended invitations, observations of behavior, and offers of presence are all therapeutic techniques.'},

{id:'PSI-014',cat:'PSI',b:0.45,type:'mc',
 stem:'A client with major depressive disorder who has been withdrawn suddenly appears calm, energetic, and begins giving away possessions. What should the nurse do?',
 options:['Praise the client for the improvement','Assess immediately for suicidal ideation and a plan','Reduce the level of observation','Encourage the client to lead a group activity'],
 answer:1,
 rationale:'A sudden lift in mood in a severely depressed client, especially with giving away possessions, is a classic warning that the client may have decided on suicide and now has the energy to act. Immediate suicide assessment and increased observation are required.'},

{id:'PSI-015',cat:'PSI',b:1.1,type:'mc',
 stem:'A client is escalating and shouting at other clients in the day room. What should the nurse do first?',
 options:['Administer an as-needed intramuscular sedative','Calmly ask the client to move to a quieter area and offer to talk','Call security to place the client in seclusion','Ignore the behavior so it is not reinforced'],
 answer:1,
 rationale:'Least restrictive interventions come first: reduce stimulation, use a calm voice, maintain safe distance, and offer verbal de-escalation. Medication, seclusion, and restraint are used only when less restrictive measures fail and safety is threatened.'},

{id:'PSI-016',cat:'PSI',b:-0.1,type:'mc',
 stem:'A dying client tells the nurse, "I just want to see my daughter graduate next month." Which stage of grief does this reflect?',
 options:['Denial','Anger','Bargaining','Acceptance'],
 answer:2,
 rationale:'Bargaining involves negotiating for more time or a different outcome, often tied to a meaningful event. Denial rejects the reality, anger externalizes distress, and acceptance is a settled awareness of the coming loss.'},

{id:'PSI-017',cat:'PSI',b:1.9,type:'mc',
 stem:'A client taking lithium reports nausea, coarse hand tremor, and unsteady gait. The lithium level is 2.1 mEq/L. What is the nurse\'s priority action?',
 options:['Withhold the next dose and notify the practitioner immediately','Encourage fluids and administer the scheduled dose','Restrict sodium intake','Reassure the client that these are expected side effects'],
 answer:0,
 rationale:'A level above 1.5 mEq/L is toxic, and 2.1 mEq/L with neurological signs is a medical emergency that can progress to seizures and coma. The dose is held and the practitioner notified. Sodium restriction raises lithium levels further and is contraindicated.'},

{id:'PSI-018',cat:'PSI',b:0.25,type:'mc',
 stem:'A client asks the nurse to pray with them before surgery. The nurse does not share the client\'s faith. What is the most appropriate response?',
 options:['"I do not share your beliefs, so I cannot help."','"I will stay with you while you pray, and I can contact the chaplain if you would like."','"Prayer will not change the outcome of surgery."','"You should ask your family to do that."'],
 answer:1,
 rationale:'Supporting spiritual needs does not require sharing the client\'s beliefs. Offering presence and access to a chaplain respects the client\'s values without requiring the nurse to participate in a way that conflicts with their own.'},

{id:'PSI-019',cat:'PSI',b:1.5,type:'matrix',
 stem:'A client is admitted with suspected intimate partner violence. Indicate whether each nursing action is indicated or contraindicated.',
 rowHeader:'Nursing action',
 rows:['Interview the client alone, without the partner present',
       'Document injuries objectively with body maps and the client\'s own words',
       'Tell the client they must leave the relationship today',
       'Provide information about local shelters and a safety plan',
       'Contact the partner to hear their explanation of the injuries'],
 cols:['Indicated','Contraindicated'],
 answer:[0,0,1,0,1],
 rationale:'Private interviewing, objective documentation, and offering resources and safety planning support the client without removing their autonomy. Insisting the client leave ignores the fact that leaving is the most dangerous period, and contacting the partner can escalate danger and breach confidentiality.'},

{id:'PSI-020',cat:'PSI',b:-0.55,type:'mc',
 stem:'A nurse is caring for a client with dementia who becomes agitated during bathing. Which approach is most appropriate?',
 options:['Complete the bath quickly despite the protest','Explain each step in simple terms, use a calm voice, and allow the client to hold a washcloth','Ask several staff members to hold the client still','Postpone all bathing indefinitely'],
 answer:1,
 rationale:'Simple step-by-step explanation, a calm approach, and giving the client a role reduce fear and resistance in dementia care. Force and multiple restraining staff escalate agitation, and indefinitely omitting hygiene neglects a basic need.'},

{id:'PSI-021',cat:'PSI',b:0.95,type:'mc',
 stem:'A client experiencing a panic attack says they cannot breathe and feels they are dying. What should the nurse do first?',
 options:['Leave the client alone to reduce stimulation','Stay with the client and guide slow, deep breathing','Explain that panic attacks are not dangerous','Administer oxygen at 6 L/min'],
 answer:1,
 rationale:'The nurse remains with the client, provides a calm presence, and coaches slow breathing. Leaving a panicked client alone increases terror, explanations are not processed during panic, and oxygen is not indicated because oxygenation is normal.'},

{id:'PSI-022',cat:'PSI',b:1.25,type:'mc',
 stem:'A client on a psychiatric unit refuses to leave their room and eats only food brought by family, stating the hospital food is poisoned. Which nursing approach is best?',
 options:['Insist the client eat the hospital food to challenge the delusion','Allow the family food and offer sealed, unopened items while building trust','Tell the client the food is not poisoned and show the kitchen','Withhold food until the client agrees to eat'],
 answer:1,
 rationale:'Delusions are not corrected by argument or proof. Offering sealed items respects the fear while meeting nutritional needs and building the trust required for treatment. Confrontation reinforces suspicion, and withholding food is punitive and unsafe.'},

{id:'PSI-023',cat:'PSI',b:-1.55,type:'mc',
 stem:'Which action best establishes a therapeutic nurse-client relationship during the orientation phase?',
 options:['Sharing personal problems to show empathy','Establishing trust, clarifying roles, and setting mutual goals','Promising to keep everything the client says secret','Making all decisions for the client'],
 answer:1,
 rationale:'The orientation phase focuses on establishing trust, defining roles and boundaries, and setting mutual goals. Self-disclosure of personal problems shifts focus to the nurse, absolute confidentiality cannot be promised when safety is at risk, and deciding for the client undermines autonomy.'},

{id:'PSI-024',cat:'PSI',b:0.15,type:'mc',
 stem:'A client in the intensive care unit has been awake for 3 days with constant lighting and alarms and now reports seeing insects on the walls. Which nursing action is most appropriate?',
 options:['Request an antipsychotic prescription','Cluster care to allow uninterrupted rest, reduce noise, and provide day-night lighting cues','Restrain the client to prevent line removal','Move the client to a windowless room'],
 answer:1,
 rationale:'These findings suggest sensory-perceptual alteration related to sleep deprivation and environmental overload. Restoring the sleep-wake cycle, reducing noise, clustering care, and providing orientation cues address the cause. Medication and restraint do not correct the underlying deprivation.'},

{id:'PSI-025',cat:'PSI',b:0.65,type:'mc',
 stem:'A nurse is assessing a client\'s coping. Which behavior indicates the use of an adaptive coping strategy?',
 options:['Drinking alcohol nightly to fall asleep','Attending a support group and using a walking routine to manage stress','Avoiding all discussion of the diagnosis','Working 80 hours a week to stay distracted'],
 answer:1,
 rationale:'Adaptive coping reduces distress without creating new problems and often involves social support and healthy activity. Substance use, avoidance, and overwork are maladaptive strategies that provide short-term relief while worsening long-term outcomes.'}

);
