/* Reduction of Risk Potential - Physiological Integrity */
(window.NCLEX_BANK = window.NCLEX_BANK || []).push(

{id:'RRP-001',cat:'RRP',b:-1.8,type:'mc',
 stem:'Which laboratory value is outside the expected reference range for an adult?',
 options:['Sodium 138 mEq/L','Potassium 6.2 mEq/L','Hemoglobin 14 g/dL','Platelets 250,000/mm3'],
 answer:1,
 rationale:'The expected potassium range is roughly 3.5 to 5.0 mEq/L, so 6.2 mEq/L is hyperkalemia and carries a risk of peaked T waves, widened QRS, and cardiac arrest. The other values are within normal limits.'},

{id:'RRP-002',cat:'RRP',b:-1.4,type:'mc',
 stem:'A client is scheduled for a magnetic resonance imaging scan. Which information must the nurse report to the radiology department?',
 options:['The client has a permanent pacemaker','The client had breakfast 4 hours ago','The client wears reading glasses','The client is 68 years old'],
 answer:0,
 rationale:'Implanted ferromagnetic devices such as many pacemakers, some aneurysm clips, and cochlear implants may be contraindicated in the magnetic field. Removable items such as glasses are simply taken off before the scan.'},

{id:'RRP-003',cat:'RRP',b:-0.9,type:'mc',
 stem:'After a cardiac catheterization through the right femoral artery, which assessment finding requires immediate action?',
 options:['A small amount of bruising at the insertion site','Absent right pedal pulses with a cool, pale foot','Blood pressure of 128/76 mm Hg','Client reports mild discomfort at the site'],
 answer:1,
 rationale:'Loss of a distal pulse with coolness and pallor suggests arterial occlusion or thrombosis distal to the puncture site and requires immediate notification. Minor bruising and mild discomfort are expected findings.'},

{id:'RRP-004',cat:'RRP',b:-0.5,type:'sata',
 stem:'A nurse is caring for a client after a bronchoscopy with moderate sedation. Which actions are appropriate? Select all that apply.',
 options:['Keep the client on nothing by mouth until the gag reflex returns','Monitor for respiratory distress and bleeding','Offer ice water immediately to soothe the throat','Position the client on their side or with the head of the bed elevated','Assess for subcutaneous emphysema around the neck','Encourage vigorous coughing every 15 minutes'],
 answer:[0,1,3,4],
 rationale:'The topical anesthetic suppresses the gag reflex, so oral intake is withheld until it returns to prevent aspiration. Monitoring for bleeding, respiratory compromise, pneumothorax, and subcutaneous emphysema is essential. Vigorous coughing may dislodge clots and provoke bleeding.'},

{id:'RRP-005',cat:'RRP',b:0.1,type:'mc',
 stem:'A client is 6 hours postoperative after abdominal surgery and has not voided. The bladder is palpable above the symphysis pubis. What should the nurse do first?',
 options:['Insert a straight catheter','Perform a bladder scan to measure the volume','Increase intravenous fluids','Notify the practitioner for a catheter order'],
 answer:1,
 rationale:'A noninvasive bladder scan quantifies the retained volume and determines whether catheterization is needed, avoiding an unnecessary invasive procedure and infection risk.'},

{id:'RRP-006',cat:'RRP',b:0.6,type:'mc',
 stem:'A client with a chest tube connected to a water-seal drainage system has continuous vigorous bubbling in the water-seal chamber. What does this most likely indicate?',
 options:['Normal function of the system','An air leak in the system or a large pneumothorax','Complete lung re-expansion','The suction is set too low'],
 answer:1,
 rationale:'Intermittent bubbling in the water-seal chamber during exhalation is expected while air is being evacuated, but continuous vigorous bubbling signals an air leak. The nurse assesses the tubing and connections and then the insertion site. Gentle continuous bubbling belongs in the suction control chamber, not the water seal.'},

{id:'RRP-007',cat:'RRP',b:1.0,type:'mc',
 stem:'A client\'s arterial blood gas results show pH 7.28, PaCO2 58 mm Hg, and HCO3 25 mEq/L. How should the nurse interpret these results?',
 options:['Respiratory acidosis, uncompensated','Metabolic acidosis, uncompensated','Respiratory alkalosis, partially compensated','Metabolic alkalosis, fully compensated'],
 answer:0,
 rationale:'The pH is low and the PaCO2 is high, so the primary problem is respiratory. Bicarbonate is normal, meaning no metabolic compensation has occurred yet, making this uncompensated respiratory acidosis.'},

{id:'RRP-008',cat:'RRP',b:1.4,type:'mc',
 stem:'A client\'s arterial blood gas results show pH 7.49, PaCO2 30 mm Hg, and HCO3 23 mEq/L. Which client situation best explains these values?',
 options:['A client hypoventilating from an opioid overdose','A client hyperventilating from acute anxiety','A client with prolonged vomiting','A client with diabetic ketoacidosis'],
 answer:1,
 rationale:'A high pH with a low PaCO2 is respiratory alkalosis, produced by blowing off carbon dioxide during hyperventilation. Opioid overdose causes respiratory acidosis, vomiting causes metabolic alkalosis, and ketoacidosis causes metabolic acidosis.'},

{id:'RRP-009',cat:'RRP',b:-1.2,type:'mc',
 stem:'A client is scheduled for a fasting blood glucose test. Which instruction is correct?',
 options:['"Do not eat or drink anything except water for 8 hours before the test."','"Eat a light breakfast before coming in."','"Drink a sugary beverage 1 hour before."','"Take all your morning medications with juice."'],
 answer:0,
 rationale:'A fasting glucose requires no caloric intake for at least 8 hours; water is permitted. Food, sugary drinks, and juice invalidate the result.'},

{id:'RRP-010',cat:'RRP',b:0.3,type:'mc',
 stem:'A nurse is monitoring a client after a liver biopsy. Which position should the nurse maintain immediately after the procedure?',
 options:['Left side-lying','Right side-lying with a pillow against the biopsy site','Prone with the head turned','High Fowler'],
 answer:1,
 rationale:'Lying on the right side applies pressure to the liver capsule and the puncture site, reducing the risk of hemorrhage and bile leak, the principal complications of liver biopsy.'},

{id:'RRP-011',cat:'RRP',b:0.75,type:'sata',
 stem:'Which findings in a postoperative client suggest hypovolemic shock? Select all that apply.',
 options:['Tachycardia with a weak thready pulse','Bounding pulses and flushed skin','Cool clammy skin','Urine output of 15 mL/hour','Narrowing pulse pressure','Increasing restlessness'],
 answer:[0,2,3,4,5],
 rationale:'Compensatory responses to volume loss include tachycardia, vasoconstriction with cool clammy skin, oliguria, a narrowed pulse pressure, and early restlessness from cerebral hypoperfusion. Bounding pulses and flushed warm skin suggest early distributive shock, not hypovolemia.'},

{id:'RRP-012',cat:'RRP',b:1.2,type:'mc',
 stem:'A client with a new tracheostomy suddenly develops respiratory distress and the nurse cannot pass a suction catheter. What should the nurse do first?',
 options:['Remove the inner cannula and attempt suctioning again','Deflate the cuff and reposition the client','Call for help and prepare for tube replacement while providing oxygen','Instill saline into the tracheostomy'],
 answer:0,
 rationale:'Obstruction of the inner cannula by dried secretions is the most common and most quickly reversible cause. Removing or replacing the inner cannula takes seconds. If distress persists, the nurse calls for help, provides oxygen, and prepares for tube replacement. Saline instillation is not recommended.'},

{id:'RRP-013',cat:'RRP',b:-0.15,type:'mc',
 stem:'Which nursing action best prevents postoperative atelectasis?',
 options:['Encouraging incentive spirometry every hour while awake','Keeping the client supine and still','Restricting fluids','Administering an antitussive around the clock'],
 answer:0,
 rationale:'Incentive spirometry with sustained maximal inspiration, combined with deep breathing, coughing, and early ambulation, keeps alveoli open. Immobility, dehydration, and suppressing the cough all promote retained secretions and collapse.'},

{id:'RRP-014',cat:'RRP',b:1.7,type:'mc',
 stem:'A client is 24 hours postoperative from a total hip arthroplasty and reports sudden dyspnea and pleuritic chest pain. Oxygen saturation is 87% and heart rate is 124/min. What should the nurse do first?',
 options:['Apply oxygen and elevate the head of the bed while calling for rapid response','Encourage the client to use the incentive spirometer','Administer the ordered opioid for pain','Ambulate the client to improve circulation'],
 answer:0,
 rationale:'These findings suggest pulmonary embolism, a leading cause of postoperative death. Oxygenation and immediate escalation come first. Ambulating a client with a suspected embolism and treating the pain without addressing hypoxemia are both unsafe.'},

{id:'RRP-015',cat:'RRP',b:0.45,type:'mc',
 stem:'A nurse reviews a client\'s laboratory results before a paracentesis. Which result should be reported to the practitioner before the procedure?',
 options:['International normalized ratio of 3.4','Albumin of 3.2 g/dL','Sodium of 136 mEq/L','White blood cell count of 8000/mm3'],
 answer:0,
 rationale:'An international normalized ratio of 3.4 indicates significant coagulopathy and greatly increases bleeding risk during an invasive procedure. The other values are normal or only mildly abnormal and do not contraindicate the procedure.'},

{id:'RRP-016',cat:'RRP',b:-0.7,type:'mc',
 stem:'A client\'s telemetry monitor shows a heart rate of 38/min. The client is dizzy and hypotensive. Which medication should the nurse anticipate?',
 options:['Atropine','Adenosine','Amiodarone','Metoprolol'],
 answer:0,
 rationale:'Atropine is first-line for symptomatic bradycardia. Adenosine treats supraventricular tachycardia, amiodarone treats ventricular and atrial tachydysrhythmias, and metoprolol would further slow the heart rate.'},

{id:'RRP-017',cat:'RRP',b:1.55,type:'mc',
 stem:'A client is receiving a continuous bladder irrigation after transurethral prostate resection. The drainage is bright red with clots and the client reports bladder spasms. What is the nurse\'s first action?',
 options:['Stop the irrigation to allow the bleeding to clot','Increase the irrigation rate and assess catheter patency','Clamp the catheter for 30 minutes','Remove the catheter'],
 answer:1,
 rationale:'Increasing the flow of irrigant and checking for obstruction clears clots that would otherwise block the catheter and cause distention and further bleeding. Stopping or clamping the irrigation promotes clot obstruction, and the catheter is not removed by the nurse.'},

{id:'RRP-018',cat:'RRP',b:0.2,type:'matrix',
 stem:'Indicate whether each laboratory result for an adult client is within the expected range or outside it.',
 rowHeader:'Laboratory result',
 rows:['Serum sodium 128 mEq/L',
       'Serum calcium 9.2 mg/dL',
       'Blood urea nitrogen 42 mg/dL',
       'Hemoglobin A1c 5.4%',
       'White blood cell count 22,000/mm3'],
 cols:['Within expected range','Outside expected range'],
 answer:[1,0,1,0,1],
 rationale:'Expected adult ranges are approximately sodium 135 to 145 mEq/L, calcium 9.0 to 10.5 mg/dL, blood urea nitrogen 10 to 20 mg/dL, hemoglobin A1c below 5.7%, and white blood cells 5000 to 10,000/mm3. Sodium 128, blood urea nitrogen 42, and a white count of 22,000 are all abnormal.'},

{id:'RRP-019',cat:'RRP',b:0.9,type:'mc',
 stem:'A client is scheduled for a computed tomography scan with iodinated contrast. Which client history requires the nurse to notify the practitioner before the study?',
 options:['A history of seasonal allergies','A serum creatinine of 2.8 mg/dL','A history of appendectomy','A blood pressure of 132/78 mm Hg'],
 answer:1,
 rationale:'Iodinated contrast is nephrotoxic, and a creatinine of 2.8 mg/dL indicates impaired renal function and a high risk of contrast-induced nephropathy. Metformin is also typically held. Seasonal allergies alone are not a contraindication, though a prior contrast reaction would be.'},

{id:'RRP-020',cat:'RRP',b:-1.05,type:'mc',
 stem:'Which finding should the nurse expect when assessing a client with a well-functioning arteriovenous fistula?',
 options:['A palpable thrill and audible bruit','Absent pulses distal to the site','Cool skin over the fistula','A firm, hard, pulseless cord'],
 answer:0,
 rationale:'A thrill felt on palpation and a bruit heard on auscultation confirm patency and flow. Absent thrill and bruit indicate thrombosis and require immediate notification. Blood pressure, venipuncture, and intravenous lines are never used in the fistula arm.'},

{id:'RRP-021',cat:'RRP',b:1.85,type:'mc',
 stem:'A client with a head injury has a Glasgow Coma Scale score that drops from 14 to 9, with a widening pulse pressure and bradycardia. What do these findings indicate?',
 options:['Improving neurological status','Increasing intracranial pressure with Cushing triad','Hypovolemic shock','Normal postinjury variation'],
 answer:1,
 rationale:'Widening pulse pressure, bradycardia, and irregular respirations make up Cushing triad, a late sign of dangerously increased intracranial pressure. Combined with a falling Glasgow Coma Scale score, this is a neurosurgical emergency.'},

{id:'RRP-022',cat:'RRP',b:0.55,type:'sata',
 stem:'Which actions should the nurse take to reduce the risk of a surgical site infection? Select all that apply.',
 options:['Ensure prophylactic antibiotics are given within the recommended window before incision','Remove hair with clippers rather than a razor if hair removal is necessary','Maintain normothermia during the perioperative period','Keep blood glucose well controlled in the perioperative period','Change the initial surgical dressing every 2 hours','Use sterile technique for dressing changes'],
 answer:[0,1,2,3,5],
 rationale:'Timely prophylaxis, clipping rather than shaving, normothermia, glycemic control, and sterile technique are all evidence-based prevention measures. The initial surgical dressing is usually left undisturbed for the period specified by the surgeon rather than changed frequently.'},

{id:'RRP-023',cat:'RRP',b:-0.35,type:'mc',
 stem:'A nurse is preparing a client for a lumbar puncture. Which position should the nurse assist the client into?',
 options:['Prone with arms overhead','Lateral recumbent with knees drawn to the chest and chin tucked','Supine with legs extended','Semi-Fowler with the head turned'],
 answer:1,
 rationale:'Flexing the spine in a lateral recumbent position widens the intervertebral spaces so the needle can be introduced. Sitting and leaning forward over a table is an accepted alternative.'},

{id:'RRP-024',cat:'RRP',b:1.35,type:'mc',
 stem:'A client with a nasogastric tube to continuous suction has a serum potassium of 3.0 mEq/L and a pH of 7.50. Which complication does the nurse suspect?',
 options:['Metabolic acidosis from bicarbonate loss','Metabolic alkalosis from loss of gastric acid','Respiratory acidosis from hypoventilation','Respiratory alkalosis from pain'],
 answer:1,
 rationale:'Continuous gastric suction removes hydrochloric acid and potassium, producing hypokalemic metabolic alkalosis. Losses from the lower gastrointestinal tract, in contrast, cause bicarbonate loss and metabolic acidosis.'},

{id:'RRP-025',cat:'RRP',b:0.0,type:'mc',
 stem:'Which client is at greatest risk for developing a pressure injury?',
 options:['An ambulatory client with well-controlled hypertension','An immobile client with incontinence and a serum albumin of 2.4 g/dL','A client 1 day after an outpatient hernia repair','A client with a seasonal allergy'],
 answer:1,
 rationale:'Immobility, moisture from incontinence, and malnutrition indicated by low albumin combine to create the highest risk. Mobility and adequate nutrition are strongly protective.'},

{id:'RRP-026',cat:'RRP',b:1.1,type:'mc',
 stem:'A client with acute kidney injury has a potassium level of 6.8 mEq/L. Which electrocardiogram change should the nurse look for first?',
 options:['Prominent U waves','Tall peaked T waves','Prolonged QT interval','ST elevation in the inferior leads'],
 answer:1,
 rationale:'Tall, peaked T waves are the earliest electrocardiographic sign of hyperkalemia, progressing to a widened QRS, loss of P waves, and a sine wave pattern. Prominent U waves and a prolonged QT are associated with hypokalemia and hypocalcemia.'},

{id:'RRP-027',cat:'RRP',b:-1.6,type:'mc',
 stem:'A client is scheduled for surgery in the morning. Which preoperative instruction is most important for the nurse to reinforce?',
 options:['"Take nothing by mouth after midnight as prescribed."','"Bring your own pillow."','"Wear comfortable shoes."','"Ask your family to arrive early."'],
 answer:0,
 rationale:'Fasting reduces gastric volume and the risk of aspiration during anesthesia, which is the most significant safety issue among these instructions.'},

{id:'RRP-028',cat:'RRP',b:0.65,type:'mc',
 stem:'A nurse notes that a client\'s urine output has been 25 mL/hour for the past 3 hours after major surgery. Blood pressure is 96/58 mm Hg and heart rate is 112/min. What is the nurse\'s priority action?',
 options:['Document the findings and continue to monitor','Notify the practitioner and anticipate a fluid challenge','Increase oral fluids','Insert an indwelling urinary catheter'],
 answer:1,
 rationale:'Oliguria with tachycardia and a falling blood pressure suggests hypovolemia and inadequate renal perfusion. Prompt notification and a fluid challenge address the cause. Continued observation risks progression to acute kidney injury.'},

{id:'RRP-029',cat:'RRP',b:1.45,type:'highlight',
 stem:'The nurse reviews the postoperative note below. Highlight each finding that indicates a developing complication.',
 instr:'Tap each finding that suggests a developing complication. Tap again to remove a highlight.',
 segments:[
  'The client is 18 hours after an open abdominal procedure.',
  'Temperature is 38.9 C and heart rate is 118/min.',
  'The abdominal dressing has a new area of purulent drainage.',
  'Bowel sounds are hypoactive in all four quadrants.',
  'The incision edges are separating at the lower margin.',
  'The client rates pain 3 of 10 after the scheduled analgesic.'],
 answer:[1,2,4],
 rationale:'Fever with tachycardia, purulent drainage, and separating wound edges point to infection and possible dehiscence. Hypoactive bowel sounds are expected in the first days after abdominal surgery, and pain controlled at 3 of 10 reflects effective analgesia.'},

{id:'RRP-030',cat:'RRP',b:-0.55,type:'mc',
 stem:'A nurse is caring for a client after a thyroidectomy. Which equipment should be immediately available at the bedside?',
 options:['A tracheostomy tray and calcium gluconate','A chest tube insertion kit','A lumbar puncture tray','An arterial line kit'],
 answer:0,
 rationale:'Airway obstruction from hemorrhage or laryngeal edema and hypocalcemic tetany from parathyroid injury are the two feared early complications, so a tracheostomy tray and intravenous calcium gluconate are kept at hand.'}

);
