/* Safety and Infection Prevention and Control - Safe and Effective Care Environment
   (renamed from 'Safety and Infection Control' in the April 2026 test plan;
   the content domain and the 10-16% range are unchanged) */
(window.NCLEX_BANK = window.NCLEX_BANK || []).push(

{id:'SIC-001',cat:'SIC',b:-1.8,type:'mc',
 stem:'Which action is the single most effective way to prevent the transmission of infection in the hospital?',
 options:['Wearing gloves for all client contact','Performing hand hygiene before and after client contact','Placing all clients in private rooms','Using antibiotics prophylactically'],
 answer:1,
 rationale:'Hand hygiene remains the most effective single measure to prevent health care associated infection. Gloves do not replace hand hygiene, private rooms are indicated only for specific organisms, and prophylactic antibiotics promote resistance.'},

{id:'SIC-002',cat:'SIC',b:-1.4,type:'ordered',
 stem:'Place the steps for removing personal protective equipment after leaving a contact-precautions room in the correct order.',
 options:['Remove gloves','Remove goggles or face shield','Remove gown','Remove mask or respirator','Perform hand hygiene'],
 rationale:'Gloves are the most contaminated item and come off first, followed by eye protection, then the gown. The mask or respirator is removed last, after leaving the room for airborne precautions, because it protects the airway the longest. Hand hygiene completes the sequence.'},

{id:'SIC-003',cat:'SIC',b:-0.9,type:'mc',
 stem:'A client is admitted with suspected varicella (chickenpox). Which precautions should the nurse implement?',
 options:['Contact precautions only','Droplet precautions only','Airborne and contact precautions','Standard precautions only'],
 answer:2,
 rationale:'Varicella spreads by both the airborne route and by contact with vesicular fluid, so both airborne and contact precautions are required, along with a negative-pressure room. The same combination applies to disseminated herpes zoster.'},

{id:'SIC-004',cat:'SIC',b:-0.5,type:'sata',
 stem:'Which clients require droplet precautions? Select all that apply.',
 options:['A client with bacterial meningitis caused by Neisseria meningitidis','A client with pulmonary tuberculosis','A client with influenza','A client with pertussis','A client with Clostridioides difficile diarrhea','A client with mumps'],
 answer:[0,2,3,5],
 rationale:'Droplet precautions apply to organisms spread by large respiratory droplets, including meningococcal disease, influenza, pertussis, and mumps. Tuberculosis requires airborne precautions, and C. difficile requires contact precautions with soap-and-water hand hygiene because alcohol does not kill the spores.'},

{id:'SIC-005',cat:'SIC',b:0.2,type:'mc',
 stem:'A nurse is caring for a client with Clostridioides difficile infection. Which action is essential?',
 options:['Use alcohol-based hand rub after removing gloves','Wash hands with soap and water after removing gloves','Wear an N95 respirator when entering the room','Place the client in a negative-pressure room'],
 answer:1,
 rationale:'C. difficile forms spores that are not killed by alcohol-based products. Soap-and-water handwashing physically removes spores. Contact precautions and sporicidal surface disinfection are also required; airborne measures are not.'},

{id:'SIC-006',cat:'SIC',b:-1.1,type:'mc',
 stem:'A nurse enters a client\'s room and finds a small fire in the wastebasket. Using the RACE sequence, what is the nurse\'s first action?',
 options:['Activate the fire alarm','Rescue the client from immediate danger','Confine the fire by closing doors','Extinguish the fire with an extinguisher'],
 answer:1,
 rationale:'RACE stands for Rescue, Alarm, Confine, Extinguish. Removing anyone in immediate danger comes first, then activating the alarm, closing doors to confine the fire, and finally extinguishing it if it is small and safe to do so.'},

{id:'SIC-007',cat:'SIC',b:0.6,type:'mc',
 stem:'A nurse is preparing to use a fire extinguisher. Which sequence describes correct use?',
 options:['Pull the pin, aim at the top of the flames, squeeze, sweep','Pull the pin, aim at the base of the fire, squeeze the handle, sweep side to side','Aim at the base, pull the pin, sweep, then squeeze','Squeeze the handle, pull the pin, aim high, sweep'],
 answer:1,
 rationale:'The PASS mnemonic is Pull the pin, Aim at the base of the fire, Squeeze the handle, and Sweep from side to side. Aiming at the flames rather than the fuel source is ineffective.'},

{id:'SIC-008',cat:'SIC',b:-0.2,type:'sata',
 stem:'Which interventions reduce a hospitalized older adult\'s risk of falling? Select all that apply.',
 options:['Keep the bed in the lowest position with wheels locked','Place frequently used items within reach','Use full side rails on all four corners to keep the client in bed','Ensure adequate lighting and a clear path to the bathroom','Provide nonskid footwear when ambulating','Toilet the client on a scheduled routine'],
 answer:[0,1,3,4,5],
 rationale:'Low bed height, reachable belongings, good lighting, nonskid footwear, and scheduled toileting all reduce falls. Raising all four side rails is considered a restraint and increases injury severity when a client climbs over them.'},

{id:'SIC-009',cat:'SIC',b:1.0,type:'mc',
 stem:'While preparing a sterile field, the nurse notices that the edge of the drape has touched the nurse\'s scrub top. What should the nurse do?',
 options:['Continue, since the scrub top is clean','Cover the contaminated area with a sterile towel','Consider the field contaminated and set up a new sterile field','Wipe the area with an alcohol pad'],
 answer:2,
 rationale:'Anything below waist level or in contact with a nonsterile surface is contaminated, and contamination cannot be corrected by covering or wiping. The field must be discarded and re-established.'},

{id:'SIC-010',cat:'SIC',b:0.4,type:'mc',
 stem:'A nurse sustains a needlestick from a used hollow-bore needle. What is the nurse\'s first action?',
 options:['Report the exposure to the supervisor','Wash the site with soap and running water','Request postexposure prophylaxis','Complete an incident report'],
 answer:1,
 rationale:'Immediate first aid comes first: wash the site with soap and water. Reporting, source testing, baseline testing, and evaluation for postexposure prophylaxis follow promptly, ideally within 1 to 2 hours for HIV prophylaxis.'},

{id:'SIC-011',cat:'SIC',b:-0.7,type:'mc',
 stem:'A nurse is teaching parents of a toddler about home safety. Which statement indicates that further teaching is needed?',
 options:['"We keep cleaning products in a locked cabinet."','"We turned the water heater down to 120 degrees Fahrenheit."','"We keep the poison control number on the refrigerator."','"We store the medicines on top of the refrigerator where he cannot climb."'],
 answer:3,
 rationale:'Toddlers are skilled climbers, so height alone is not a safe storage strategy. Medications require locked storage. Locked chemicals, a water heater at or below 120 F, and readily available poison control information are all correct.'},

{id:'SIC-012',cat:'SIC',b:1.3,type:'mc',
 stem:'A client receiving oxygen at 4 L/min by nasal cannula is confused and keeps removing the cannula. Which action should the nurse take first?',
 options:['Apply soft wrist restraints','Assess the client for hypoxemia and other causes of the confusion','Ask a family member to sit with the client','Switch to a nonrebreather mask'],
 answer:1,
 rationale:'Confusion may be the result of hypoxemia, hypoglycemia, infection, or medication effect. Assessment identifies and treats the cause. Restraints are a last resort after less restrictive measures fail, and changing the delivery device without assessment does not address the underlying problem.'},

{id:'SIC-013',cat:'SIC',b:0.8,type:'sata',
 stem:'A nurse is caring for a client in soft wrist restraints. Which nursing actions are required? Select all that apply.',
 options:['Tie the restraint straps to the movable side rail for easy access','Assess skin integrity and circulation at least every 2 hours','Release the restraints and provide range of motion at regular intervals','Secure the restraint with a quick-release knot to the bed frame','Obtain a renewal of the prescription according to policy and regulation','Document the client\'s behavior and the less restrictive measures attempted'],
 answer:[1,2,3,4,5],
 rationale:'Restraints are tied to a nonmovable part of the bed frame with a quick-release knot, never to a side rail, because raising the rail would injure the client. Frequent monitoring, periodic release, prescription renewal, and documentation of behavior and alternatives tried are all required.'},

{id:'SIC-014',cat:'SIC',b:-1.6,type:'mc',
 stem:'Which item requires the nurse to use surgical asepsis?',
 options:['Inserting an indwelling urinary catheter','Administering an oral medication','Emptying a urinary drainage bag','Assisting a client with a shower'],
 answer:0,
 rationale:'Insertion of an indwelling urinary catheter enters a sterile body cavity and requires sterile technique. The other tasks require clean technique and standard precautions only.'},

{id:'SIC-015',cat:'SIC',b:0.1,type:'mc',
 stem:'A nurse is caring for a client receiving internal radiation (brachytherapy) for cervical cancer. Which action is appropriate?',
 options:['Encourage visitors to stay as long as they wish','Keep a lead container and long forceps in the room','Provide care while standing at the head of the bed for extended periods','Allow a pregnant staff member to care for the client'],
 answer:1,
 rationale:'A lead container and forceps must be immediately available in case the implant becomes dislodged; the implant is never touched with bare hands. Time near the client is minimized, distance is maximized, shielding is used, and pregnant staff and children are not assigned or permitted to visit.'},

{id:'SIC-016',cat:'SIC',b:1.6,type:'mc',
 stem:'A nurse is reviewing safe practice for medication administration. Which strategy best prevents a wrong-client error?',
 options:['Checking the room number against the medication administration record','Using two client identifiers such as name and date of birth','Asking the client, "Are you Mr. Jones?"','Relying on the wristband color'],
 answer:1,
 rationale:'Two client identifiers that are not location-based are required. Room numbers change, leading questions invite an incorrect confirmation from a confused client, and wristband color coding varies among facilities.'},

{id:'SIC-017',cat:'SIC',b:-0.4,type:'mc',
 stem:'When using proper body mechanics to move a client up in bed, which action should the nurse take?',
 options:['Bend at the waist and keep the knees straight','Raise the bed to waist height and use a friction-reducing device with a second staff member','Twist at the trunk while pulling the client toward the head of the bed','Reach across the bed to pull the client from the far side'],
 answer:1,
 rationale:'Safe client handling raises the work surface to waist level, uses friction-reducing devices, and adds staff to distribute the load. Bending at the waist, twisting, and reaching across the bed all increase the risk of injury to the nurse.'},

{id:'SIC-018',cat:'SIC',b:0.9,type:'mc',
 stem:'A client with neutropenia is placed on protective precautions. Which action by the unlicensed assistive personnel requires the nurse to intervene?',
 options:['Performing hand hygiene before entering the room','Bringing the client a vase of fresh cut flowers','Assisting the client with oral care using a soft toothbrush','Wearing a mask when the staff member has a mild cough'],
 answer:1,
 rationale:'Fresh flowers and standing water harbor Aspergillus and Pseudomonas and are prohibited for neutropenic clients, as are raw fruits and vegetables in many protocols. The other actions are appropriate protective measures.'},

{id:'SIC-019',cat:'SIC',b:1.9,type:'mc',
 stem:'During an external disaster with many incoming casualties, the charge nurse must create bed capacity. Which client is most appropriate to discharge first?',
 options:['A client 3 days after an uncomplicated laparoscopic cholecystectomy who is tolerating diet and ambulating','A client receiving intravenous vasopressors','A client 12 hours after a myocardial infarction','A client with new-onset seizures awaiting neurology consultation'],
 answer:0,
 rationale:'The stable postoperative client meeting discharge criteria can safely continue recovery at home. The other three require ongoing monitoring or intervention that cannot be provided outside the hospital.'},

{id:'SIC-020',cat:'SIC',b:-1.2,type:'mc',
 stem:'A nurse notices a client\'s intravenous pump has a frayed electrical cord. What should the nurse do first?',
 options:['Wrap the cord with tape and continue use','Remove the pump from service and obtain a replacement','Report it to biomedical engineering at the end of the shift','Plug the pump into a different outlet'],
 answer:1,
 rationale:'Damaged electrical equipment poses a shock and fire hazard and must be removed from service immediately and replaced, then tagged and sent for repair. Taping, delaying, or changing outlets does not remove the hazard.'},

{id:'SIC-021',cat:'SIC',b:0.3,type:'matrix',
 stem:'For each client, indicate the type of transmission-based precautions required.',
 rowHeader:'Client',
 rows:['A client with active pulmonary tuberculosis',
       'A client with methicillin-resistant Staphylococcus aureus in a draining wound',
       'A client with rubeola (measles)',
       'A client with Neisseria meningitidis meningitis',
       'A client with respiratory syncytial virus bronchiolitis'],
 cols:['Airborne','Droplet','Contact'],
 answer:[0,2,0,1,2],
 rationale:'Tuberculosis and measles are airborne. Meningococcal meningitis is droplet. MRSA wound drainage and respiratory syncytial virus are spread by contact, although many facilities add droplet precautions for RSV as well.'},

{id:'SIC-022',cat:'SIC',b:0.7,type:'mc',
 stem:'A nurse is preparing to administer a chemotherapeutic agent. Which personal protective equipment is required?',
 options:['Clean gloves only','Two pairs of chemotherapy-tested gloves and a closed-front impervious gown','Sterile gloves and a surgical mask','An N95 respirator and a face shield only'],
 answer:1,
 rationale:'Hazardous drug handling requires double chemotherapy-tested gloves and a closed-front, back-closing impervious gown, with eye and respiratory protection added when splashing or aerosolization is possible. Standard clean gloves do not provide adequate barrier protection.'},

{id:'SIC-023',cat:'SIC',b:-0.6,type:'mc',
 stem:'The nurse is caring for a client at risk for seizures. Which item should be at the bedside?',
 options:['A padded tongue blade','Suction equipment and oxygen','Soft wrist restraints','A cooling blanket'],
 answer:1,
 rationale:'Suction and oxygen are needed to protect the airway during and after a seizure. Nothing is ever placed in the mouth of a seizing client, and restraints can cause injury during tonic-clonic activity.'},

{id:'SIC-024',cat:'SIC',b:1.4,type:'sata',
 stem:'A nurse is implementing measures to prevent a central line associated bloodstream infection. Which actions are correct? Select all that apply.',
 options:['Perform hand hygiene before accessing the line','Scrub the needleless connector with an antiseptic for the recommended time before each access','Change the transparent dressing whenever it is damp, loosened, or soiled','Review daily whether the catheter is still necessary','Use the central line for routine blood draws whenever it is convenient','Use maximal sterile barrier precautions during insertion'],
 answer:[0,1,2,3,5],
 rationale:'Hand hygiene, scrubbing the hub, dressing integrity, daily review of necessity, and maximal barriers at insertion are the core bundle elements. Minimizing line access, rather than using the line for convenience, further reduces infection risk.'},

{id:'SIC-025',cat:'SIC',b:2.1,type:'mc',
 stem:'A nurse is triaging clients after a chemical spill involving an unknown liquid. What is the priority action before clients enter the emergency department?',
 options:['Obtain a detailed history of the exposure','Decontaminate clients by removing clothing and irrigating the skin','Administer activated charcoal','Start intravenous access on all clients'],
 answer:1,
 rationale:'Decontamination protects the client, the staff, and the facility and must occur before clients enter the treatment area. Removing clothing eliminates a large proportion of contaminant, followed by copious water irrigation. History and treatment follow decontamination.'},

{id:'SIC-026',cat:'SIC',b:-0.05,type:'mc',
 stem:'A nurse is teaching an older adult about home fall prevention. Which client statement indicates correct understanding?',
 options:['"I will keep small throw rugs by the door so my feet stay warm."','"I will install grab bars in the shower and beside the toilet."','"I will get up quickly in the morning so I do not get stiff."','"I will keep the hallway light off at night to save electricity."'],
 answer:1,
 rationale:'Grab bars provide support at the highest-risk locations. Throw rugs are a leading trip hazard, rising quickly worsens orthostatic hypotension, and night lighting along the path to the bathroom is essential.'},

{id:'SIC-027',cat:'SIC',b:1.1,type:'mc',
 stem:'A nurse is caring for a client with a latex allergy. Which action is most important?',
 options:['Place a sign on the door and use latex-free supplies including gloves, tourniquets, and catheters','Keep an antihistamine at the bedside','Ask the client to avoid touching equipment','Use powdered latex gloves only when necessary'],
 answer:0,
 rationale:'Prevention through a latex-free environment is the priority, because exposure can trigger anaphylaxis. Latex is present in many items beyond gloves, including tourniquets, blood pressure cuff tubing, and some catheters. Powdered latex gloves are especially hazardous because the powder aerosolizes the allergen.'},

{id:'SIC-028',cat:'SIC',b:0.5,type:'mc',
 stem:'The nurse is caring for a client in the postanesthesia care unit who is at risk for aspiration. Which position is most appropriate while the client is still drowsy and has an intact gag reflex?',
 options:['Supine with the head flat','Lateral (side-lying) recovery position','High Fowler with the neck flexed','Trendelenburg'],
 answer:1,
 rationale:'The lateral recovery position allows secretions to drain from the mouth and keeps the tongue from occluding the airway. Supine and neck flexion increase aspiration and obstruction risk, and Trendelenburg promotes reflux toward the airway.'},

{id:'SIC-029',cat:'SIC',b:-1.0,type:'mc',
 stem:'Which action by a nursing student demonstrates correct use of a gait belt when ambulating a client?',
 options:['Applying the belt over the client\'s bare abdomen and grasping the client\'s arm','Applying the belt snugly around the waist over clothing and grasping it underhand from behind and slightly to the side','Applying the belt over the chest and pulling the client forward','Holding the belt with one hand while carrying the intravenous pole with the other'],
 answer:1,
 rationale:'The gait belt is applied over clothing at the waist, snug enough to admit only a flat hand, and grasped underhand while the nurse stands slightly behind and to the side on the client\'s weaker side. Managing equipment single-handedly leaves the nurse unable to support a fall.'},

{id:'SIC-030',cat:'SIC',b:0.25,type:'mc',
 stem:'The nurse reviews four newly written prescriptions. Which one must be clarified because it uses an abbreviation on the "do not use" list?',
 options:['"Insulin glargine 20 U subcutaneously at bedtime"','"Digoxin 0.125 mg orally daily"','"Morphine 2 mg IV every 4 hours as needed for pain"','"Levothyroxine 75 mcg orally daily"'],
 answer:0,
 rationale:'The abbreviation "U" for units is on the official do-not-use list because it is easily misread as a zero or a four, producing a tenfold insulin overdose. The word units must be written out. A leading zero before a decimal point, as in 0.125 mg, is correct; it is the trailing zero that is prohibited.'},

{id:'SIC-031',cat:'SIC',b:1.7,type:'highlight',
 stem:'A nurse reviews a shift report. Highlight each finding that indicates an immediate safety risk requiring intervention.',
 instr:'Tap each phrase that represents an immediate safety risk. Tap again to remove a highlight.',
 segments:[
  'The client is oriented to person only and has attempted to climb over the bed rail twice.',
  'The bed is in the low position with the wheels locked.',
  'The client received lorazepam 2 mg IV thirty minutes ago and is now unsteady when standing.',
  'The call light is clipped to the sheet at the foot of the bed out of reach.',
  'Nonskid socks are on the client\'s feet.',
  'The intravenous pole and a chair are blocking the path to the bathroom.'],
 answer:[0,2,3,5],
 rationale:'Attempting to climb over rails, recent sedation with unsteadiness, an out-of-reach call light, and a blocked path to the bathroom are all active fall and injury risks that require immediate correction. A low locked bed and nonskid footwear are appropriate safety measures.'},

{id:'SIC-032',cat:'SIC',b:-1.7,type:'mc',
 stem:'Before administering a blood transfusion, which action is essential?',
 options:['Verify client identity and blood product with a second qualified staff member','Warm the blood in a microwave','Prime the tubing with dextrose 5% in water','Administer the unit over 6 hours'],
 answer:0,
 rationale:'A two-person verification of the client identifiers and the unit is the key defense against a fatal ABO incompatibility. Blood is primed with normal saline only, never warmed in a microwave, and each unit must infuse within 4 hours to limit bacterial growth.'}

);
