/**
 * Role-contract generation.
 *
 * The contracts in `agents/residents/` are the human-readable face of the roster in
 * `packages/core/src/residents.ts`. They are generated, not hand-written, because a role
 * contract that has drifted from the permissions actually enforced is worse than no contract
 * at all — it documents an organization that does not exist.
 *
 * `evals/contracts.test.ts` fails if the checked-in files no longer match this output.
 */

import { RESIDENTS, DOMAIN_OWNER, MODEL_ROUTES, QUALITY_COUNCIL, district, type Resident } from "@agent-city/core";

export function renderContract(r: Resident): string {
  const route = MODEL_ROUTES[r.modelClass];
  const home = district(r.district);
  const verifiedBy = RESIDENTS.filter((o) => o.id !== r.id && r.implementsDomains.some((d) => o.verifiesDomains.includes(d)));

  return `<!-- generated by scripts/contracts.ts — edit packages/core/src/residents.ts instead -->

# ${r.name} — ${r.title}

**Location** ${home.name} · **Reports to** ${r.reportsTo ?? "the owner"} · **Default route** \`${route.model}\`${route.effort ? ` · effort \`${route.effort}\`` : ""}${route.thinking ? ` · thinking \`${route.thinking.type}\`` : " · no extended thinking"}

${r.appearance}

## Authority

${r.authority}.

${r.releaseAuthority ? "Holds **release authority** — the only resident who does. It may approve only against a complete evidence manifest, and the approval is itself an irreversible action requiring an owner grant.\n" : ""}
## Domains

| | |
| --- | --- |
| Produces work in | ${r.implementsDomains.length > 0 ? r.implementsDomains.map((d) => `\`${d}\``).join(", ") : "—"} |
| Renders independent verdicts on | ${r.verifiesDomains.length > 0 ? r.verifiesDomains.map((d) => `\`${d}\``).join(", ") : "—"} |
| Its own work is judged by | ${verifiedBy.length > 0 ? verifiedBy.map((o) => o.name).join(", ") : "— (no independent verifier: this is a governance defect)"} |

${r.implementsDomains.some((d) => r.verifiesDomains.includes(d)) ? "> ⚠ This resident both produces and judges the same domain. Article 6 forbids it.\n" : ""}
## Output contract

An output missing any of these fields is not a submission:

${r.outputContract.map((f) => `- \`${f}\``).join("\n")}

## Tool envelope

The envelope is **closed by default** — a tool that appears in neither list is denied, and
deny always beats allow.

**Allowed**

${r.tools.allow.map((t) => `- \`${t}\``).join("\n")}

**Denied**

${r.tools.deny.length > 0 ? r.tools.deny.map((t) => `- \`${t}\``).join("\n") : "- (nothing beyond the organization-wide denials)"}

## Memory

Private namespace \`${r.memoryNamespace}\`. No other resident reads it.

## Standing obligations

- A task is not complete because you believe it is complete.
- A claim is not true because you are confident; every material claim carries an evidence pointer.
- Report what you could not establish as plainly as what you could.
- You never grade your own work.
${QUALITY_COUNCIL.includes(r.id) ? "- You sit on the Adversarial Quality Council. Your verdict alone can block a release, and a pass you cannot evidence is a fail.\n" : ""}`;
}

export function renderIndex(): string {
  return `<!-- generated by scripts/contracts.ts — edit packages/core/src/residents.ts instead -->

# The resident intelligence community

Fifteen permanent identities, one per durable organizational competency. Permanent identity is
*not* a unit of parallelism — massive temporary parallelism lives underneath these roles as
ephemeral workers that are created for one bounded problem and then released.

The names and coats make the organization legible. They do not create the competence.
Competence comes from model selection, context, the role contract, the tool envelope, memory,
and above all from the fact that nobody here grades their own work.

| Resident | Responsibility | District | Route | Authority |
| --- | --- | --- | --- | --- |
${RESIDENTS.map((r) => {
  const route = MODEL_ROUTES[r.modelClass];
  return `| [${r.name}](residents/${r.id}.md) | ${r.title} | ${district(r.district).name} | \`${route.model}\` | ${r.authority} |`;
}).join("\n")}

## Domain ownership

Exactly one resident owns each domain. Contribution is plural; accountability is singular.

${Object.entries(DOMAIN_OWNER).map(([d, o]) => `- \`${d}\` → **${o}**`).join("\n")}

## The Adversarial Quality Council

${QUALITY_COUNCIL.map((id) => `- **${id}** — ${RESIDENTS.find((r) => r.id === id)!.title}`).join("\n")}

Any one of them can block a release on their own verdict. None of them can approve one; that
is Pax's alone, and only against a complete evidence manifest.

## Growing the roster

New residents are not added by editing this file. A capability gap is *measured* from what a
run actually cost, a genome is drafted, and the candidate is refused four times over before it
is admitted — see [\`../docs/GENESIS.md\`](../docs/GENESIS.md) and
[\`genomes/\`](genomes/) for a worked example.
`;
}
